// AUTO-GENERATED from egytrains.com – do not edit by hand.
// Extra stations discovered from live schedule data.
import type { Station } from './stations';

export const EXTRA_STATIONS: readonly Station[] = [
  { id: "abo-mashhour", code: "ABO", line: "cairo-alexandria", name: { en: "Abo Mashhour", ar: "ابو مشهور" }, city: { en: "Abo Mashhour", ar: "ابو مشهور" } },
  { id: "arab-raml", code: "ARA", line: "cairo-alexandria", name: { en: "Arab Raml", ar: "عرب الرمل" }, city: { en: "Arab Raml", ar: "عرب الرمل" } },
  { id: "sandanhour", code: "SAN", line: "cairo-alexandria", name: { en: "Sandanhour", ar: "سندنهور" }, city: { en: "Sandanhour", ar: "سندنهور" } },
  { id: "semad-talkha", code: "SEM", line: "delta", name: { en: "Semad Talkha", ar: "سماد طلخا" }, city: { en: "Semad Talkha", ar: "سماد طلخا" } },
  { id: "mit-antar", code: "MIT", line: "delta", name: { en: "Mit Antar", ar: "ميت عنتر" }, city: { en: "Mit Antar", ar: "ميت عنتر" } },
  { id: "shirinqash", code: "SHI", line: "delta", name: { en: "Shirinqash", ar: "شرنقاش" }, city: { en: "Shirinqash", ar: "شرنقاش" } },
  { id: "tawilah", code: "TAW", line: "delta", name: { en: "Tawilah", ar: "الطويلة" }, city: { en: "Tawilah", ar: "الطويلة" } },
  { id: "daysat", code: "DAY", line: "delta", name: { en: "Daysat", ar: "ديسط" }, city: { en: "Daysat", ar: "ديسط" } },
  { id: "batrah", code: "BAT", line: "delta", name: { en: "Batrah", ar: "بطره" }, city: { en: "Batrah", ar: "بطره" } },
  { id: "hag-khaleel", code: "HAG", line: "delta", name: { en: "Hag Khaleel", ar: "الحاج خليل" }, city: { en: "Hag Khaleel", ar: "الحاج خليل" } },
  { id: "kafr-hatabah", code: "KAF", line: "delta", name: { en: "Kafr Hatabah", ar: "كفر الحطبه" }, city: { en: "Kafr Hatabah", ar: "كفر الحطبه" } },
  { id: "kafr-dabbusi", code: "KAF", line: "delta", name: { en: "Kafr Dabbusi", ar: "كفر الدبوسي" }, city: { en: "Kafr Dabbusi", ar: "كفر الدبوسي" } },
  { id: "shirbin", code: "SHI", line: "delta", name: { en: "Shirbin", ar: "شربين" }, city: { en: "Shirbin", ar: "شربين" } },
  { id: "saadwa", code: "SAA", line: "delta", name: { en: "Saadwa", ar: "السعادوه" }, city: { en: "Saadwa", ar: "السعادوه" } },
  { id: "sabreyah", code: "SAB", line: "delta", name: { en: "Sabreyah", ar: "الصبرية" }, city: { en: "Sabreyah", ar: "الصبرية" } },
  { id: "ras-khaleej", code: "RAS", line: "delta", name: { en: "Ras Khaleej", ar: "راس الخليج" }, city: { en: "Ras Khaleej", ar: "راس الخليج" } },
  { id: "gamasa", code: "GAM", line: "delta", name: { en: "Gamasa", ar: "جمصة" }, city: { en: "Gamasa", ar: "جمصة" } },
  { id: "swalem", code: "SWA", line: "delta", name: { en: "Swalem", ar: "السوالم" }, city: { en: "Swalem", ar: "السوالم" } },
  { id: "kafr-saad-b", code: "KAF", line: "delta", name: { en: "Kafr Saad B", ar: "كفر سعد البلد" }, city: { en: "Kafr Saad B", ar: "كفر سعد البلد" } },
  { id: "kafr-saad", code: "KAF", line: "delta", name: { en: "Kafr Saad", ar: "كفر سعد" }, city: { en: "Kafr Saad", ar: "كفر سعد" } },
  { id: "tawfiqiah-b", code: "TAW", line: "delta", name: { en: "Tawfiqiah B", ar: "التوفيقية البلد" }, city: { en: "Tawfiqiah B", ar: "التوفيقية البلد" } },
  { id: "kafr-battikh", code: "KAF", line: "delta", name: { en: "Kafr Battikh", ar: "كفر البطيخ" }, city: { en: "Kafr Battikh", ar: "كفر البطيخ" } },
  { id: "basatin-kafr-battikh", code: "BAS", line: "delta", name: { en: "Basatin Kafr Battikh", ar: "بساتين كفر البطيخ" }, city: { en: "Basatin Kafr Battikh", ar: "بساتين كفر البطيخ" } },
  { id: "mit-korma", code: "MIT", line: "delta", name: { en: "Mit Korma", ar: "ميت الكرما" }, city: { en: "Mit Korma", ar: "ميت الكرما" } },
  { id: "kafr-arab", code: "KAF", line: "delta", name: { en: "Kafr Arab", ar: "كفر العرب" }, city: { en: "Kafr Arab", ar: "كفر العرب" } },
  { id: "mit-assas", code: "MIT", line: "delta", name: { en: "Mit Assas", ar: "ميت عساس" }, city: { en: "Mit Assas", ar: "ميت عساس" } },
  { id: "mit-khalaf", code: "MIT", line: "delta", name: { en: "Mit Khalaf", ar: "ميت خلف" }, city: { en: "Mit Khalaf", ar: "ميت خلف" } },
  { id: "rahbayn", code: "RAH", line: "delta", name: { en: "Rahbayn", ar: "الراهبين" }, city: { en: "Rahbayn", ar: "الراهبين" } },
  { id: "mahallat-abo-ali-qantara", code: "MAH", line: "delta", name: { en: "Mahallat Abo Ali Qantara", ar: "محلة ابو على القنطرة" }, city: { en: "Mahallat Abo Ali Qantara", ar: "محلة ابو على القنطرة" } },
  { id: "ghazl-mahalla", code: "GHA", line: "delta", name: { en: "Ghazl Mahalla", ar: "غزل المحلة" }, city: { en: "Ghazl Mahalla", ar: "غزل المحلة" } },
  { id: "mahalla-kubra", code: "MAH", line: "delta", name: { en: "Mahalla Kubra", ar: "المحلة الكبرى" }, city: { en: "Mahalla Kubra", ar: "المحلة الكبرى" } },
  { id: "manshyt-bakry", code: "MAN", line: "delta", name: { en: "Manshyt Bakry", ar: "منشية البكري" }, city: { en: "Manshyt Bakry", ar: "منشية البكري" } },
  { id: "minyat-shentena-ayash", code: "MIN", line: "delta", name: { en: "Minyat Shentena Ayash", ar: "منية شنتا عياش" }, city: { en: "Minyat Shentena Ayash", ar: "منية شنتا عياش" } },
  { id: "saft-turab", code: "SAF", line: "delta", name: { en: "Saft Turab", ar: "صفط تراب" }, city: { en: "Saft Turab", ar: "صفط تراب" } },
  { id: "mahallat-rouh", code: "MAH", line: "delta", name: { en: "Mahallat Rouh", ar: "محلة روح" }, city: { en: "Mahallat Rouh", ar: "محلة روح" } },
  { id: "shebshir-hessah", code: "SHE", line: "delta", name: { en: "Shebshir Hessah", ar: "شبشير الحصة" }, city: { en: "Shebshir Hessah", ar: "شبشير الحصة" } },
  { id: "ragdiah", code: "RAG", line: "delta", name: { en: "Ragdiah", ar: "الرجدية" }, city: { en: "Ragdiah", ar: "الرجدية" } },
  { id: "upper-egypt", code: "UPP", line: "upper-egypt", name: { en: "Upper Egypt", ar: "صعيد مصر" }, city: { en: "Upper Egypt", ar: "صعيد مصر" } },
  { id: "hawamdeyya", code: "HAW", line: "upper-egypt", name: { en: "Hawamdeyya", ar: "الحوامدية" }, city: { en: "Hawamdeyya", ar: "الحوامدية" } },
  { id: "badrshein", code: "BAD", line: "upper-egypt", name: { en: "Badrshein", ar: "البدرشين" }, city: { en: "Badrshein", ar: "البدرشين" } },
  { id: "ayat", code: "AYA", line: "upper-egypt", name: { en: "Ayat", ar: "العياط" }, city: { en: "Ayat", ar: "العياط" } },
  { id: "wasta", code: "WAS", line: "upper-egypt", name: { en: "Wasta", ar: "الواسطى" }, city: { en: "Wasta", ar: "الواسطى" } },
  { id: "nasser", code: "NAS", line: "upper-egypt", name: { en: "Nasser", ar: "ناصر" }, city: { en: "Nasser", ar: "ناصر" } },
  { id: "biba", code: "BIB", line: "upper-egypt", name: { en: "Biba", ar: "ببا" }, city: { en: "Biba", ar: "ببا" } },
  { id: "fashn", code: "FAS", line: "upper-egypt", name: { en: "Fashn", ar: "الفشن" }, city: { en: "Fashn", ar: "الفشن" } },
  { id: "aba-wakf", code: "ABA", line: "upper-egypt", name: { en: "Aba Wakf", ar: "ابا الوقف" }, city: { en: "Aba Wakf", ar: "ابا الوقف" } },
  { id: "matay", code: "MAT", line: "upper-egypt", name: { en: "Matay", ar: "مطاي" }, city: { en: "Matay", ar: "مطاي" } },
  { id: "samalut", code: "SAM", line: "upper-egypt", name: { en: "Samalut", ar: "سملوط" }, city: { en: "Samalut", ar: "سملوط" } },
  { id: "damaris", code: "DAM", line: "upper-egypt", name: { en: "Damaris", ar: "دماريس" }, city: { en: "Damaris", ar: "دماريس" } },
  { id: "abo-qurqas", code: "ABO", line: "upper-egypt", name: { en: "Abo Qurqas", ar: "ابو قرقاص" }, city: { en: "Abo Qurqas", ar: "ابو قرقاص" } },
  { id: "rawda", code: "RAW", line: "upper-egypt", name: { en: "Rawda", ar: "الروضة" }, city: { en: "Rawda", ar: "الروضة" } },
  { id: "dayr-mawas", code: "DAY", line: "upper-egypt", name: { en: "Dayr Mawas", ar: "دير مواس" }, city: { en: "Dayr Mawas", ar: "دير مواس" } },
  { id: "dayrout", code: "DAY", line: "upper-egypt", name: { en: "Dayrout", ar: "ديروط" }, city: { en: "Dayrout", ar: "ديروط" } },
  { id: "qusiyyah", code: "QUS", line: "upper-egypt", name: { en: "Qusiyyah", ar: "القوصية" }, city: { en: "Qusiyyah", ar: "القوصية" } },
  { id: "manqabad", code: "MAN", line: "upper-egypt", name: { en: "Manqabad", ar: "منقباد" }, city: { en: "Manqabad", ar: "منقباد" } },
  { id: "abo-tij", code: "ABO", line: "upper-egypt", name: { en: "Abo Tij", ar: "ابو تيج" }, city: { en: "Abo Tij", ar: "ابو تيج" } },
  { id: "maragha", code: "MAR", line: "upper-egypt", name: { en: "Maragha", ar: "المراغة" }, city: { en: "Maragha", ar: "المراغة" } },
  { id: "monshaa", code: "MON", line: "upper-egypt", name: { en: "Monshaa", ar: "المنشأة" }, city: { en: "Monshaa", ar: "المنشأة" } },
  { id: "usayrat", code: "USA", line: "upper-egypt", name: { en: "Usayrat", ar: "العسيرات" }, city: { en: "Usayrat", ar: "العسيرات" } },
  { id: "bardis", code: "BAR", line: "upper-egypt", name: { en: "Bardis", ar: "برديس" }, city: { en: "Bardis", ar: "برديس" } },
  { id: "abo-shousha", code: "ABO", line: "upper-egypt", name: { en: "Abo Shousha", ar: "ابو شوشة" }, city: { en: "Abo Shousha", ar: "ابو شوشة" } },
  { id: "abo-tesht", code: "ABO", line: "upper-egypt", name: { en: "Abo Tesht", ar: "ابو تشت" }, city: { en: "Abo Tesht", ar: "ابو تشت" } },
  { id: "farshut", code: "FAR", line: "upper-egypt", name: { en: "Farshut", ar: "فرشوط" }, city: { en: "Farshut", ar: "فرشوط" } },
  { id: "nagaa-hammadi", code: "NAG", line: "upper-egypt", name: { en: "Nagaa Hammadi", ar: "نجع حمادي" }, city: { en: "Nagaa Hammadi", ar: "نجع حمادي" } },
  { id: "dishna", code: "DIS", line: "upper-egypt", name: { en: "Dishna", ar: "دشنا" }, city: { en: "Dishna", ar: "دشنا" } },
  { id: "qift", code: "QIF", line: "upper-egypt", name: { en: "Qift", ar: "قفط" }, city: { en: "Qift", ar: "قفط" } },
  { id: "qus", code: "QUS", line: "upper-egypt", name: { en: "Qus", ar: "قوص" }, city: { en: "Qus", ar: "قوص" } },
  { id: "armant", code: "ARM", line: "upper-egypt", name: { en: "Armant", ar: "ارمنت" }, city: { en: "Armant", ar: "ارمنت" } },
  { id: "sharawnah", code: "SHA", line: "upper-egypt", name: { en: "Sharawnah", ar: "الشراونة" }, city: { en: "Sharawnah", ar: "الشراونة" } },
  { id: "sibaiyyah", code: "SIB", line: "upper-egypt", name: { en: "Sibaiyyah", ar: "السباعية" }, city: { en: "Sibaiyyah", ar: "السباعية" } },
  { id: "mahamid", code: "MAH", line: "upper-egypt", name: { en: "Mahamid", ar: "المحاميد" }, city: { en: "Mahamid", ar: "المحاميد" } },
  { id: "radisia", code: "RAD", line: "upper-egypt", name: { en: "Radisia", ar: "الرديسية" }, city: { en: "Radisia", ar: "الرديسية" } },
  { id: "ramadi", code: "RAM", line: "upper-egypt", name: { en: "Ramadi", ar: "الرمادي" }, city: { en: "Ramadi", ar: "الرمادي" } },
  { id: "silwa-bahari", code: "SIL", line: "upper-egypt", name: { en: "Silwa Bahari", ar: "سلوا" }, city: { en: "Silwa Bahari", ar: "سلوا" } },
  { id: "kalabsha", code: "KAL", line: "upper-egypt", name: { en: "Kalabsha", ar: "كلابشة" }, city: { en: "Kalabsha", ar: "كلابشة" } },
  { id: "ballana", code: "BAL", line: "upper-egypt", name: { en: "Ballana", ar: "بلانة" }, city: { en: "Ballana", ar: "بلانة" } },
  { id: "sheikh-haroun", code: "SHE", line: "upper-egypt", name: { en: "Sheikh Haroun", ar: "الشيخ هارون" }, city: { en: "Sheikh Haroun", ar: "الشيخ هارون" } },
  { id: "kima", code: "KIM", line: "upper-egypt", name: { en: "Kima", ar: "كيما" }, city: { en: "Kima", ar: "كيما" } },
  { id: "sadaka", code: "SAD", line: "upper-egypt", name: { en: "Sadaka", ar: "الصداقة" }, city: { en: "Sadaka", ar: "الصداقة" } },
  { id: "the-high-dam", code: "THE", line: "upper-egypt", name: { en: "The High Dam", ar: "السد العالي" }, city: { en: "The High Dam", ar: "السد العالي" } },
  { id: "amer", code: "AME", line: "canal", name: { en: "Amer", ar: "عامر" }, city: { en: "Amer", ar: "عامر" } },
  { id: "ganayen", code: "GAN", line: "canal", name: { en: "Ganayen", ar: "الجناين" }, city: { en: "Ganayen", ar: "الجناين" } },
  { id: "shaloofh", code: "SHA", line: "canal", name: { en: "Shaloofh", ar: "شلوفة" }, city: { en: "Shaloofh", ar: "شلوفة" } },
  { id: "64-km", code: "64-", line: "canal", name: { en: "64 km", ar: "كيلو 64" }, city: { en: "64 km", ar: "كيلو 64" } },
  { id: "abo-halab", code: "ABO", line: "canal", name: { en: "Abo halab", ar: "ابو حلب" }, city: { en: "Abo halab", ar: "ابو حلب" } },
  { id: "jenefh", code: "JEN", line: "canal", name: { en: "Jenefh", ar: "جنيفة" }, city: { en: "Jenefh", ar: "جنيفة" } },
  { id: "kasfareet", code: "KAS", line: "canal", name: { en: "kasfareet", ar: "كسفريت" }, city: { en: "kasfareet", ar: "كسفريت" } },
  { id: "fanara", code: "FAN", line: "canal", name: { en: "Fanara", ar: "فنارة" }, city: { en: "Fanara", ar: "فنارة" } },
  { id: "kemt-fayed", code: "KEM", line: "canal", name: { en: "Kemt Fayed", ar: "قمة فايد" }, city: { en: "Kemt Fayed", ar: "قمة فايد" } },
  { id: "fayed-n", code: "FAY", line: "canal", name: { en: "Fayed N", ar: "فايد ج" }, city: { en: "Fayed N", ar: "فايد ج" } },
  { id: "fayed", code: "FAY", line: "canal", name: { en: "Fayed", ar: "فايد" }, city: { en: "Fayed", ar: "فايد" } },
  { id: "saidia", code: "SAI", line: "canal", name: { en: "Saidia", ar: "السعيدية" }, city: { en: "Saidia", ar: "السعيدية" } },
  { id: "abo-sultan", code: "ABO", line: "canal", name: { en: "Abo Sultan", ar: "ابو سلطان" }, city: { en: "Abo Sultan", ar: "ابو سلطان" } },
  { id: "10th-of-ramadan", code: "10T", line: "canal", name: { en: "10th of Ramadan", ar: "10 رمضان" }, city: { en: "10th of Ramadan", ar: "10 رمضان" } },
  { id: "serapeum", code: "SER", line: "canal", name: { en: "Serapeum", ar: "سرابيوم" }, city: { en: "Serapeum", ar: "سرابيوم" } },
  { id: "ain-ghoseen", code: "AIN", line: "canal", name: { en: "Ain Ghoseen", ar: "عين غصين" }, city: { en: "Ain Ghoseen", ar: "عين غصين" } },
  { id: "ad-dabiyyah", code: "AD-", line: "canal", name: { en: "Ad Dabiyyah", ar: "الضبعية" }, city: { en: "Ad Dabiyyah", ar: "الضبعية" } },
  { id: "nafesha", code: "NAF", line: "canal", name: { en: "Nafesha", ar: "نفيشة" }, city: { en: "Nafesha", ar: "نفيشة" } },
  { id: "galaa-camp", code: "GAL", line: "canal", name: { en: "Galaa Camp", ar: "معسكر الجلاء" }, city: { en: "Galaa Camp", ar: "معسكر الجلاء" } },
  { id: "tala", code: "TAL", line: "cairo-alexandria", name: { en: "Tala", ar: "تلا" }, city: { en: "Tala", ar: "تلا" } },
  { id: "batanun", code: "BAT", line: "cairo-alexandria", name: { en: "Batanun", ar: "البتانون" }, city: { en: "Batanun", ar: "البتانون" } },
  { id: "shebeen-kom-n", code: "SHE", line: "cairo-alexandria", name: { en: "Shebeen Kom N", ar: "شبين الكوم ج" }, city: { en: "Shebeen Kom N", ar: "شبين الكوم ج" } },
  { id: "shebeen-kom-o", code: "SHE", line: "cairo-alexandria", name: { en: "Shebeen Kom O", ar: "شبين الكوم ق" }, city: { en: "Shebeen Kom O", ar: "شبين الكوم ق" } },
  { id: "shanawan", code: "SHA", line: "cairo-alexandria", name: { en: "Shanawan", ar: "شنوان" }, city: { en: "Shanawan", ar: "شنوان" } },
  { id: "hamoul", code: "HAM", line: "cairo-alexandria", name: { en: "Hamoul", ar: "الحامول" }, city: { en: "Hamoul", ar: "الحامول" } },
  { id: "minuf", code: "MIN", line: "cairo-alexandria", name: { en: "Minuf", ar: "منوف" }, city: { en: "Minuf", ar: "منوف" } },
  { id: "samadun", code: "SAM", line: "cairo-alexandria", name: { en: "Samadun", ar: "سمادون" }, city: { en: "Samadun", ar: "سمادون" } },
  { id: "ashmun", code: "ASH", line: "cairo-alexandria", name: { en: "Ashmun", ar: "اشمون" }, city: { en: "Ashmun", ar: "اشمون" } },
  { id: "hilwasi", code: "HIL", line: "cairo-alexandria", name: { en: "Hilwasi", ar: "الحلواصي" }, city: { en: "Hilwasi", ar: "الحلواصي" } },
  { id: "hilwasi-b", code: "HIL", line: "cairo-alexandria", name: { en: "Hilwasi B", ar: "الحلواصي البلد" }, city: { en: "Hilwasi B", ar: "الحلواصي البلد" } },
  { id: "shatanof", code: "SHA", line: "cairo-alexandria", name: { en: "Shatanof", ar: "شطانوف" }, city: { en: "Shatanof", ar: "شطانوف" } },
  { id: "derwah", code: "DER", line: "cairo-alexandria", name: { en: "Derwah", ar: "دروة" }, city: { en: "Derwah", ar: "دروة" } },
  { id: "qanatir-n", code: "QAN", line: "cairo-alexandria", name: { en: "Qanatir N", ar: "القناطر ج" }, city: { en: "Qanatir N", ar: "القناطر ج" } },
  { id: "qalyoub-b", code: "QAL", line: "cairo-alexandria", name: { en: "Qalyoub B", ar: "قليوب البلد" }, city: { en: "Qalyoub B", ar: "قليوب البلد" } },
  { id: "ramlat-injib", code: "RAM", line: "cairo-alexandria", name: { en: "Ramlat Injib", ar: "رملة الأنجب" }, city: { en: "Ramlat Injib", ar: "رملة الأنجب" } },
  { id: "shalaqan", code: "SHA", line: "cairo-alexandria", name: { en: "Shalaqan", ar: "شلقان" }, city: { en: "Shalaqan", ar: "شلقان" } },
  { id: "kafr-sarawah", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Sarawah", ar: "كفر صراوة" }, city: { en: "Kafr Sarawah", ar: "كفر صراوة" } },
  { id: "mahallat-subk", code: "MAH", line: "cairo-alexandria", name: { en: "Mahallat Subk", ar: "محلة سبك" }, city: { en: "Mahallat Subk", ar: "محلة سبك" } },
  { id: "badr-mosque", code: "BAD", line: "cairo-alexandria", name: { en: "Badr Mosque", ar: "جامع بدر" }, city: { en: "Badr Mosque", ar: "جامع بدر" } },
  { id: "shama", code: "SHA", line: "cairo-alexandria", name: { en: "Shama", ar: "شما" }, city: { en: "Shama", ar: "شما" } },
  { id: "kamshush", code: "KAM", line: "cairo-alexandria", name: { en: "Kamshush", ar: "كمشوش" }, city: { en: "Kamshush", ar: "كمشوش" } },
  { id: "kafr-sanabisah", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Sanabisah", ar: "كفر السنابسة" }, city: { en: "Kafr Sanabisah", ar: "كفر السنابسة" } },
  { id: "tanbadi", code: "TAN", line: "cairo-alexandria", name: { en: "Tanbadi", ar: "طنبدي" }, city: { en: "Tanbadi", ar: "طنبدي" } },
  { id: "kafr-batanun", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Batanun", ar: "كفر البتانون" }, city: { en: "Kafr Batanun", ar: "كفر البتانون" } },
  { id: "kafr-tabluha", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Tabluha", ar: "كفر طبلوها" }, city: { en: "Kafr Tabluha", ar: "كفر طبلوها" } },
  { id: "kafr-selim", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Selim", ar: "كفر سليم" }, city: { en: "Kafr Selim", ar: "كفر سليم" } },
  { id: "faiyum", code: "FAI", line: "upper-egypt", name: { en: "Faiyum", ar: "الفيوم" }, city: { en: "Faiyum", ar: "الفيوم" } },
  { id: "amereyat-fayoum", code: "AME", line: "upper-egypt", name: { en: "Amereyat Fayoum", ar: "عامرية الفيوم" }, city: { en: "Amereyat Fayoum", ar: "عامرية الفيوم" } },
  { id: "edwah", code: "EDW", line: "upper-egypt", name: { en: "Edwah", ar: "العدوة" }, city: { en: "Edwah", ar: "العدوة" } },
  { id: "sila", code: "SIL", line: "upper-egypt", name: { en: "Sila", ar: "سيلا" }, city: { en: "Sila", ar: "سيلا" } },
  { id: "nasiriyah", code: "NAS", line: "upper-egypt", name: { en: "Nasiriyah", ar: "الناصرية" }, city: { en: "Nasiriyah", ar: "الناصرية" } },
  { id: "rous", code: "ROU", line: "upper-egypt", name: { en: "Rous", ar: "الروس" }, city: { en: "Rous", ar: "الروس" } },
  { id: "werash", code: "WER", line: "upper-egypt", name: { en: "werash", ar: "الورش" }, city: { en: "werash", ar: "الورش" } },
  { id: "kom-abo-rady", code: "KOM", line: "upper-egypt", name: { en: "Kom Abo Rady", ar: "كوم أبو راضي" }, city: { en: "Kom Abo Rady", ar: "كوم أبو راضي" } },
  { id: "atwab", code: "ATW", line: "upper-egypt", name: { en: "Atwab", ar: "اطواب" }, city: { en: "Atwab", ar: "اطواب" } },
  { id: "raqqah", code: "RAQ", line: "upper-egypt", name: { en: "Raqqah", ar: "الرقة" }, city: { en: "Raqqah", ar: "الرقة" } },
  { id: "qotouri", code: "QOT", line: "upper-egypt", name: { en: "Qotouri", ar: "القطورى" }, city: { en: "Qotouri", ar: "القطورى" } },
  { id: "kafr-ammar", code: "KAF", line: "upper-egypt", name: { en: "Kafr Ammar", ar: "كفر عمار" }, city: { en: "Kafr Ammar", ar: "كفر عمار" } },
  { id: "mit-qayed", code: "MIT", line: "upper-egypt", name: { en: "Mit Qayed", ar: "ميت القايد" }, city: { en: "Mit Qayed", ar: "ميت القايد" } },
  { id: "matanyah", code: "MAT", line: "upper-egypt", name: { en: "Matanyah", ar: "المتانية" }, city: { en: "Matanyah", ar: "المتانية" } },
  { id: "blida", code: "BLI", line: "upper-egypt", name: { en: "Blida", ar: "البليدة" }, city: { en: "Blida", ar: "البليدة" } },
  { id: "mazghounah", code: "MAZ", line: "upper-egypt", name: { en: "Mazghounah", ar: "المزغونة" }, city: { en: "Mazghounah", ar: "المزغونة" } },
  { id: "maraziq", code: "MAR", line: "upper-egypt", name: { en: "Maraziq", ar: "المرازيق" }, city: { en: "Maraziq", ar: "المرازيق" } },
  { id: "kajuj", code: "KAJ", line: "upper-egypt", name: { en: "Kajuj", ar: "كاجوج" }, city: { en: "Kajuj", ar: "كاجوج" } },
  { id: "salheya", code: "SAL", line: "canal", name: { en: "Salheya", ar: "الصالحية" }, city: { en: "Salheya", ar: "الصالحية" } },
  { id: "kabaysha", code: "KAB", line: "canal", name: { en: "Kabaysha", ar: "الكابيشة" }, city: { en: "Kabaysha", ar: "الكابيشة" } },
  { id: "azzazi", code: "AZZ", line: "canal", name: { en: "Azzazi", ar: "العزازي" }, city: { en: "Azzazi", ar: "العزازي" } },
  { id: "abaza", code: "ABA", line: "canal", name: { en: "Abaza", ar: "اباظة" }, city: { en: "Abaza", ar: "اباظة" } },
  { id: "drakh", code: "DRA", line: "canal", name: { en: "Drakh", ar: "الدراكة" }, city: { en: "Drakh", ar: "الدراكة" } },
  { id: "akyad", code: "AKY", line: "canal", name: { en: "Akyad", ar: "اكياد" }, city: { en: "Akyad", ar: "اكياد" } },
  { id: "kafr-haj-omar", code: "KAF", line: "canal", name: { en: "Kafr Haj Omar", ar: "كفر الحاج عمر" }, city: { en: "Kafr Haj Omar", ar: "كفر الحاج عمر" } },
  { id: "geheinah", code: "GEH", line: "canal", name: { en: "Geheinah", ar: "جهينة" }, city: { en: "Geheinah", ar: "جهينة" } },
  { id: "bayrum", code: "BAY", line: "canal", name: { en: "Bayrum", ar: "البيروم" }, city: { en: "Bayrum", ar: "البيروم" } },
  { id: "fadadnah", code: "FAD", line: "canal", name: { en: "Fadadnah", ar: "الفدادنة" }, city: { en: "Fadadnah", ar: "الفدادنة" } },
  { id: "khalafallah", code: "KHA", line: "canal", name: { en: "Khalafallah", ar: "خلف الله" }, city: { en: "Khalafallah", ar: "خلف الله" } },
  { id: "ghaba", code: "GHA", line: "canal", name: { en: "Ghaba", ar: "الغابة" }, city: { en: "Ghaba", ar: "الغابة" } },
  { id: "abo-kibir", code: "ABO", line: "cairo-alexandria", name: { en: "Abo Kibir", ar: "ابو كبير" }, city: { en: "Abo Kibir", ar: "ابو كبير" } },
  { id: "abo-yassin", code: "ABO", line: "cairo-alexandria", name: { en: "Abo Yassin", ar: "ابو ياسين" }, city: { en: "Abo Yassin", ar: "ابو ياسين" } },
  { id: "shirshimah", code: "SHI", line: "cairo-alexandria", name: { en: "Shirshimah", ar: "شرشيمة" }, city: { en: "Shirshimah", ar: "شرشيمة" } },
  { id: "hihya", code: "HIH", line: "cairo-alexandria", name: { en: "Hihya", ar: "هيها" }, city: { en: "Hihya", ar: "هيها" } },
  { id: "adawyh", code: "ADA", line: "cairo-alexandria", name: { en: "Adawyh", ar: "العداوية" }, city: { en: "Adawyh", ar: "العداوية" } },
  { id: "kafr-msalamya", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Msalamya", ar: "كفر المسلمية" }, city: { en: "Kafr Msalamya", ar: "كفر المسلمية" } },
  { id: "harayah-raznah", code: "HAR", line: "cairo-alexandria", name: { en: "Harayah Raznah", ar: "هرية رزنة" }, city: { en: "Harayah Raznah", ar: "هرية رزنة" } },
  { id: "menyet-qamh", code: "MEN", line: "canal", name: { en: "Menyet Qamh", ar: "منية القمح" }, city: { en: "Menyet Qamh", ar: "منية القمح" } },
  { id: "abo-hammad", code: "ABO", line: "canal", name: { en: "Abo Hammad", ar: "ابو حماد" }, city: { en: "Abo Hammad", ar: "ابو حماد" } },
  { id: "tal-kabeer", code: "TAL", line: "canal", name: { en: "Tal Kabeer", ar: "التل الكبير" }, city: { en: "Tal Kabeer", ar: "التل الكبير" } },
  { id: "abo-swer", code: "ABO", line: "canal", name: { en: "Abo Swer", ar: "ابو صوير" }, city: { en: "Abo Swer", ar: "ابو صوير" } },
  { id: "qantara-gharb", code: "QAN", line: "canal", name: { en: "Qantara Gharb", ar: "القنطرة غرب" }, city: { en: "Qantara Gharb", ar: "القنطرة غرب" } },
  { id: "matariyah", code: "MAT", line: "delta", name: { en: "Matariyah", ar: "المطرية" }, city: { en: "Matariyah", ar: "المطرية" } },
  { id: "asafrah-manzalah", code: "ASA", line: "delta", name: { en: "Asafrah Manzalah", ar: "عصافرة المنزلة" }, city: { en: "Asafrah Manzalah", ar: "عصافرة المنزلة" } },
  { id: "dar-salam", code: "DAR", line: "delta", name: { en: "Dar Salam", ar: "دار السلام" }, city: { en: "Dar Salam", ar: "دار السلام" } },
  { id: "manzalah", code: "MAN", line: "delta", name: { en: "Manzalah", ar: "المنزلة" }, city: { en: "Manzalah", ar: "المنزلة" } },
  { id: "mit-khodeir", code: "MIT", line: "delta", name: { en: "Mit Khodeir", ar: "ميت خضير" }, city: { en: "Mit Khodeir", ar: "ميت خضير" } },
  { id: "jamaliyah", code: "JAM", line: "delta", name: { en: "Jamaliyah", ar: "الجمالية" }, city: { en: "Jamaliyah", ar: "الجمالية" } },
  { id: "mit-marga-selsil", code: "MIT", line: "delta", name: { en: "Mit Marga Selsil", ar: "ميت مرجا سلسيل" }, city: { en: "Mit Marga Selsil", ar: "ميت مرجا سلسيل" } },
  { id: "mit-salsil", code: "MIT", line: "delta", name: { en: "Mit Salsil", ar: "ميت سلسيل" }, city: { en: "Mit Salsil", ar: "ميت سلسيل" } },
  { id: "kurdi", code: "KUR", line: "delta", name: { en: "kurdi", ar: "الكردي" }, city: { en: "kurdi", ar: "الكردي" } },
  { id: "riyad", code: "RIY", line: "delta", name: { en: "Riyad", ar: "الرياض" }, city: { en: "Riyad", ar: "الرياض" } },
  { id: "kafr-allam", code: "KAF", line: "delta", name: { en: "Kafr Allam", ar: "كفر علام" }, city: { en: "Kafr Allam", ar: "كفر علام" } },
  { id: "mit-asem", code: "MIT", line: "delta", name: { en: "Mit Asem", ar: "ميت عاصم" }, city: { en: "Mit Asem", ar: "ميت عاصم" } },
  { id: "mit-hadid", code: "MIT", line: "delta", name: { en: "Mit Hadid", ar: "ميت حديد" }, city: { en: "Mit Hadid", ar: "ميت حديد" } },
  { id: "mit-khouly", code: "MIT", line: "delta", name: { en: "Mit Khouly", ar: "ميت الخولي" }, city: { en: "Mit Khouly", ar: "ميت الخولي" } },
  { id: "ashmoun-romman", code: "ASH", line: "delta", name: { en: "Ashmoun Romman", ar: "اشمون الرمان" }, city: { en: "Ashmoun Romman", ar: "اشمون الرمان" } },
  { id: "mit-sharaf", code: "MIT", line: "delta", name: { en: "Mit Sharaf", ar: "ميت شرف" }, city: { en: "Mit Sharaf", ar: "ميت شرف" } },
  { id: "dikirnis", code: "DIK", line: "delta", name: { en: "Dikirnis", ar: "دكرنس" }, city: { en: "Dikirnis", ar: "دكرنس" } },
  { id: "khashashnah", code: "KHA", line: "delta", name: { en: "Khashashnah", ar: "الخشاشنة" }, city: { en: "Khashashnah", ar: "الخشاشنة" } },
  { id: "mit-dafer", code: "MIT", line: "delta", name: { en: "Mit Dafer", ar: "ميت ضافر" }, city: { en: "Mit Dafer", ar: "ميت ضافر" } },
  { id: "mahallat-damanah", code: "MAH", line: "delta", name: { en: "Mahallat Damanah", ar: "محلة دمنة" }, city: { en: "Mahallat Damanah", ar: "محلة دمنة" } },
  { id: "shuha", code: "SHU", line: "delta", name: { en: "Shuha", ar: "شها" }, city: { en: "Shuha", ar: "شها" } },
  { id: "salamoun", code: "SAL", line: "delta", name: { en: "Salamoun", ar: "سلامون" }, city: { en: "Salamoun", ar: "سلامون" } },
  { id: "danabiq", code: "DAN", line: "delta", name: { en: "Danabiq", ar: "الدنابيق" }, city: { en: "Danabiq", ar: "الدنابيق" } },
  { id: "sandub", code: "SAN", line: "cairo-alexandria", name: { en: "Sandub", ar: "سندوب" }, city: { en: "Sandub", ar: "سندوب" } },
  { id: "zagazig-university", code: "ZAG", line: "canal", name: { en: "Zagazig University", ar: "جامعة الزقازيق" }, city: { en: "Zagazig University", ar: "جامعة الزقازيق" } },
  { id: "shibat-nakariyah", code: "SHI", line: "canal", name: { en: "Shibat Nakariyah", ar: "شيبة النكارية" }, city: { en: "Shibat Nakariyah", ar: "شيبة النكارية" } },
  { id: "kafr-ashraf", code: "KAF", line: "canal", name: { en: "Kafr Ashraf", ar: "كفر الاشراف" }, city: { en: "Kafr Ashraf", ar: "كفر الاشراف" } },
  { id: "naghas", code: "NAG", line: "canal", name: { en: "Naghas", ar: "النخاس" }, city: { en: "Naghas", ar: "النخاس" } },
  { id: "kafr-halaby", code: "KAF", line: "canal", name: { en: "Kafr Halaby", ar: "كفر الحلبي" }, city: { en: "Kafr Halaby", ar: "كفر الحلبي" } },
  { id: "om-zein", code: "OM-", line: "canal", name: { en: "Om Zein", ar: "ام الزين" }, city: { en: "Om Zein", ar: "ام الزين" } },
  { id: "mit-abo-orabi", code: "MIT", line: "canal", name: { en: "Mit Abo Orabi", ar: "ميت ابو العربي" }, city: { en: "Mit Abo Orabi", ar: "ميت ابو العربي" } },
  { id: "mit-qershi", code: "MIT", line: "canal", name: { en: "Mit Qershi", ar: "ميت القرشي" }, city: { en: "Mit Qershi", ar: "ميت القرشي" } },
  { id: "tafhna-ashraf", code: "TAF", line: "canal", name: { en: "Tafhna Ashraf", ar: "تفهنا الاشراف" }, city: { en: "Tafhna Ashraf", ar: "تفهنا الاشراف" } },
  { id: "kafr-wazir", code: "KAF", line: "canal", name: { en: "Kafr Wazir", ar: "كفر الوزير" }, city: { en: "Kafr Wazir", ar: "كفر الوزير" } },
  { id: "dandit", code: "DAN", line: "canal", name: { en: "Dandit", ar: "دنديط" }, city: { en: "Dandit", ar: "دنديط" } },
  { id: "mit-ghamer", code: "MIT", line: "canal", name: { en: "Mit Ghamer", ar: "ميت غمر" }, city: { en: "Mit Ghamer", ar: "ميت غمر" } },
  { id: "zefta", code: "ZEF", line: "canal", name: { en: "Zefta", ar: "زفتى" }, city: { en: "Zefta", ar: "زفتى" } },
  { id: "nahtay", code: "NAH", line: "canal", name: { en: "Nahtay", ar: "نهطاي" }, city: { en: "Nahtay", ar: "نهطاي" } },
  { id: "samlaweyah", code: "SAM", line: "canal", name: { en: "Samlaweyah", ar: "السملاوية" }, city: { en: "Samlaweyah", ar: "السملاوية" } },
  { id: "monshaah-kubra", code: "MON", line: "canal", name: { en: "Monshaah Kubra", ar: "المنشأة الكبرى" }, city: { en: "Monshaah Kubra", ar: "المنشأة الكبرى" } },
  { id: "major-abd-satar", code: "MAJ", line: "canal", name: { en: "Major Abd Satar", ar: "عبد الستار" }, city: { en: "Major Abd Satar", ar: "عبد الستار" } },
  { id: "santa", code: "SAN", line: "cairo-alexandria", name: { en: "Santa", ar: "السنطة" }, city: { en: "Santa", ar: "السنطة" } },
  { id: "shobraqas", code: "SHO", line: "cairo-alexandria", name: { en: "Shobraqas", ar: "شبراقاص" }, city: { en: "Shobraqas", ar: "شبراقاص" } },
  { id: "mit-hebeish-q", code: "MIT", line: "cairo-alexandria", name: { en: "Mit Hebeish Q", ar: "ميت حبيش ق" }, city: { en: "Mit Hebeish Q", ar: "ميت حبيش ق" } },
  { id: "kom-nour", code: "KOM", line: "cairo-alexandria", name: { en: "Kom Nour", ar: "كوم النور" }, city: { en: "Kom Nour", ar: "كوم النور" } },
  { id: "menyet-sebaa", code: "MEN", line: "canal", name: { en: "Menyet Sebaa", ar: "منية السباع" }, city: { en: "Menyet Sebaa", ar: "منية السباع" } },
  { id: "shiblanjah", code: "SHI", line: "canal", name: { en: "Shiblanjah", ar: "شبلنجة" }, city: { en: "Shiblanjah", ar: "شبلنجة" } },
  { id: "aziziyyah", code: "AZI", line: "cairo-alexandria", name: { en: "Aziziyyah", ar: "العزيزية" }, city: { en: "Aziziyyah", ar: "العزيزية" } },
  { id: "kom-halin", code: "KOM", line: "canal", name: { en: "Kom Halin", ar: "كوم حلين" }, city: { en: "Kom Halin", ar: "كوم حلين" } },
  { id: "mit-yazid", code: "MIT", line: "canal", name: { en: "Mit Yazid", ar: "ميت يزيد" }, city: { en: "Mit Yazid", ar: "ميت يزيد" } },
  { id: "jadidah", code: "JAD", line: "canal", name: { en: "Jadidah", ar: "الجديدة" }, city: { en: "Jadidah", ar: "الجديدة" } },
  { id: "qaraqrah", code: "QAR", line: "canal", name: { en: "Qaraqrah", ar: "القراقرة" }, city: { en: "Qaraqrah", ar: "القراقرة" } },
  { id: "az-zanklun", code: "AZ-", line: "canal", name: { en: "AZ Zanklun", ar: "الزنكلون" }, city: { en: "AZ Zanklun", ar: "الزنكلون" } },
  { id: "shabanat", code: "SHA", line: "canal", name: { en: "Shabanat", ar: "الشبانات" }, city: { en: "Shabanat", ar: "الشبانات" } },
  { id: "saft-hinnah", code: "SAF", line: "canal", name: { en: "Saft Hinnah", ar: "صفط الحنة" }, city: { en: "Saft Hinnah", ar: "صفط الحنة" } },
  { id: "sawah", code: "SAW", line: "canal", name: { en: "Sawah", ar: "الصوة" }, city: { en: "Sawah", ar: "الصوة" } },
  { id: "mahjar-abo-hammad", code: "MAH", line: "canal", name: { en: "Mahjar Abo Hammad", ar: "محجر ابو حماد" }, city: { en: "Mahjar Abo Hammad", ar: "محجر ابو حماد" } },
  { id: "baalwh", code: "BAA", line: "canal", name: { en: "Baalwh", ar: "البعالوة" }, city: { en: "Baalwh", ar: "البعالوة" } },
  { id: "mahsmh", code: "MAH", line: "canal", name: { en: "Mahsmh", ar: "المحسمة" }, city: { en: "Mahsmh", ar: "المحسمة" } },
  { id: "mohamed-baghdady", code: "MOH", line: "canal", name: { en: "mohamed Baghdady", ar: "محمد البغدادي" }, city: { en: "mohamed Baghdady", ar: "محمد البغدادي" } },
  { id: "abo-gresh", code: "ABO", line: "canal", name: { en: "Abo Gresh", ar: "ابو جريش" }, city: { en: "Abo Gresh", ar: "ابو جريش" } },
  { id: "wasfih", code: "WAS", line: "canal", name: { en: "Wasfih", ar: "الواصفية" }, city: { en: "Wasfih", ar: "الواصفية" } },
  { id: "sheikh-zayed", code: "SHE", line: "canal", name: { en: "Sheikh Zayed", ar: "الشيخ زايد" }, city: { en: "Sheikh Zayed", ar: "الشيخ زايد" } },
  { id: "ferdan", code: "FER", line: "canal", name: { en: "Ferdan", ar: "الفردان" }, city: { en: "Ferdan", ar: "الفردان" } },
  { id: "balah", code: "BAL", line: "canal", name: { en: "Balah", ar: "البلاح" }, city: { en: "Balah", ar: "البلاح" } },
  { id: "tenh", code: "TEN", line: "canal", name: { en: "Tenh", ar: "التينة" }, city: { en: "Tenh", ar: "التينة" } },
  { id: "cap", code: "CAP", line: "canal", name: { en: "Cap", ar: "الكاب" }, city: { en: "Cap", ar: "الكاب" } },
  { id: "ras-esh", code: "RAS", line: "canal", name: { en: "Ras Esh", ar: "راس العش" }, city: { en: "Ras Esh", ar: "راس العش" } },
  { id: "raswaa", code: "RAS", line: "canal", name: { en: "Raswaa", ar: "الرسوة" }, city: { en: "Raswaa", ar: "الرسوة" } },
  { id: "samla", code: "SAM", line: "north-coast", name: { en: "Samla", ar: "سملا" }, city: { en: "Samla", ar: "سملا" } },
  { id: "grawlah", code: "GRA", line: "north-coast", name: { en: "Grawlah", ar: "جرولة" }, city: { en: "Grawlah", ar: "جرولة" } },
  { id: "sidi-henash", code: "SID", line: "north-coast", name: { en: "Sidi Henash", ar: "سيدي حنيش" }, city: { en: "Sidi Henash", ar: "سيدي حنيش" } },
  { id: "ras-hekmah", code: "RAS", line: "north-coast", name: { en: "Ras Hekmah", ar: "راس الحكمة" }, city: { en: "Ras Hekmah", ar: "راس الحكمة" } },
  { id: "fokah", code: "FOK", line: "north-coast", name: { en: "Fokah", ar: "فوكة" }, city: { en: "Fokah", ar: "فوكة" } },
  { id: "galal", code: "GAL", line: "north-coast", name: { en: "Galal", ar: "جلال" }, city: { en: "Galal", ar: "جلال" } },
  { id: "sidi-abd-rahman", code: "SID", line: "north-coast", name: { en: "Sidi Abd Rahman", ar: "سيدي عبد الرحمن" }, city: { en: "Sidi Abd Rahman", ar: "سيدي عبد الرحمن" } },
  { id: "rowaysat", code: "ROW", line: "north-coast", name: { en: "Rowaysat", ar: "الرويسات" }, city: { en: "Rowaysat", ar: "الرويسات" } },
  { id: "hammam", code: "HAM", line: "north-coast", name: { en: "Hammam", ar: "الحمام" }, city: { en: "Hammam", ar: "الحمام" } },
  { id: "burj-arab-o", code: "BUR", line: "north-coast", name: { en: "Burj Arab O", ar: "برج العرب" }, city: { en: "Burj Arab O", ar: "برج العرب" } },
  { id: "baheeg", code: "BAH", line: "north-coast", name: { en: "Baheeg", ar: "بهيج" }, city: { en: "Baheeg", ar: "بهيج" } },
  { id: "burj-arab-airport", code: "BUR", line: "north-coast", name: { en: "Burj Arab Airport", ar: "مطار برج العرب" }, city: { en: "Burj Arab Airport", ar: "مطار برج العرب" } },
  { id: "maryout", code: "MAR", line: "north-coast", name: { en: "Maryout", ar: "مريوط" }, city: { en: "Maryout", ar: "مريوط" } },
  { id: "ekeingy-maryout", code: "EKE", line: "north-coast", name: { en: "Ekeingy Maryout", ar: "ايكنجي مريوط" }, city: { en: "Ekeingy Maryout", ar: "ايكنجي مريوط" } },
  { id: "amreyah", code: "AMR", line: "north-coast", name: { en: "Amreyah", ar: "العامرية" }, city: { en: "Amreyah", ar: "العامرية" } },
  { id: "abd-qader", code: "ABD", line: "north-coast", name: { en: "Abd Qader", ar: "عبد القادر" }, city: { en: "Abd Qader", ar: "عبد القادر" } },
  { id: "genenet-qbaary", code: "GEN", line: "north-coast", name: { en: "Genenet Qbaary", ar: "جنينة القباري" }, city: { en: "Genenet Qbaary", ar: "جنينة القباري" } },
  { id: "moharam-beek", code: "MOH", line: "north-coast", name: { en: "Moharam Beek", ar: "محرم بك" }, city: { en: "Moharam Beek", ar: "محرم بك" } },
  { id: "shibin-qanatir", code: "SHI", line: "cairo-alexandria", name: { en: "Shibin Qanatir", ar: "شبين القناطر" }, city: { en: "Shibin Qanatir", ar: "شبين القناطر" } },
  { id: "kafr-shebeen", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Shebeen", ar: "كفر شبين" }, city: { en: "Kafr Shebeen", ar: "كفر شبين" } },
  { id: "tahanub", code: "TAH", line: "cairo-alexandria", name: { en: "Tahanub", ar: "طحانوب" }, city: { en: "Tahanub", ar: "طحانوب" } },
  { id: "kafr-taha", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Taha", ar: "كفر طحا" }, city: { en: "Kafr Taha", ar: "كفر طحا" } },
  { id: "zahawiyin", code: "ZAH", line: "cairo-alexandria", name: { en: "Zahawiyin", ar: "الزهوين" }, city: { en: "Zahawiyin", ar: "الزهوين" } },
  { id: "nawa", code: "NAW", line: "cairo-alexandria", name: { en: "Nawa", ar: "نوى" }, city: { en: "Nawa", ar: "نوى" } },
  { id: "kafr-ramadah", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Ramadah", ar: "كفر رمادة" }, city: { en: "Kafr Ramadah", ar: "كفر رمادة" } },
  { id: "zawya-hamraa", code: "ZAW", line: "cairo-alexandria", name: { en: "Zawya Hamraa", ar: "الزاوية الحمراء" }, city: { en: "Zawya Hamraa", ar: "الزاوية الحمراء" } },
  { id: "shawah", code: "SHA", line: "cairo-alexandria", name: { en: "Shawah", ar: "شاوة" }, city: { en: "Shawah", ar: "شاوة" } },
  { id: "baqliyyah", code: "BAQ", line: "cairo-alexandria", name: { en: "Baqliyyah", ar: "البقلية" }, city: { en: "Baqliyyah", ar: "البقلية" } },
  { id: "zurayqi", code: "ZUR", line: "cairo-alexandria", name: { en: "Zurayqi", ar: "الزريقي" }, city: { en: "Zurayqi", ar: "الزريقي" } },
  { id: "shobra-qubala", code: "SHO", line: "cairo-alexandria", name: { en: "Shobra Qubala", ar: "شبرا قبالة" }, city: { en: "Shobra Qubala", ar: "شبرا قبالة" } },
  { id: "senbellawein", code: "SEN", line: "cairo-alexandria", name: { en: "Senbellawein", ar: "السنبلاوين" }, city: { en: "Senbellawein", ar: "السنبلاوين" } },
  { id: "taranis-arab", code: "TAR", line: "cairo-alexandria", name: { en: "Taranis Arab", ar: "طرانيس العرب" }, city: { en: "Taranis Arab", ar: "طرانيس العرب" } },
  { id: "barqin", code: "BAR", line: "cairo-alexandria", name: { en: "Barqin", ar: "برقين" }, city: { en: "Barqin", ar: "برقين" } },
  { id: "hikal-basha", code: "HIK", line: "cairo-alexandria", name: { en: "Hikal Basha", ar: "هيكل باشا" }, city: { en: "Hikal Basha", ar: "هيكل باشا" } },
  { id: "abo-shuquq", code: "ABO", line: "cairo-alexandria", name: { en: "Abo Shuquq", ar: "ابو الشقوق" }, city: { en: "Abo Shuquq", ar: "ابو الشقوق" } },
  { id: "badawy", code: "BAD", line: "cairo-alexandria", name: { en: "Badawy", ar: "بدوي" }, city: { en: "Badawy", ar: "بدوي" } },
  { id: "kafr-saqr", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Saqr", ar: "كفر صقر" }, city: { en: "Kafr Saqr", ar: "كفر صقر" } },
  { id: "bouha", code: "BOU", line: "cairo-alexandria", name: { en: "Bouha", ar: "البوها" }, city: { en: "Bouha", ar: "البوها" } },
  { id: "nazlet-khayal", code: "NAZ", line: "cairo-alexandria", name: { en: "Nazlet Khayal", ar: "نزلة الخيال" }, city: { en: "Nazlet Khayal", ar: "نزلة الخيال" } },
  { id: "bardein", code: "BAR", line: "cairo-alexandria", name: { en: "Bardein", ar: "بردين" }, city: { en: "Bardein", ar: "بردين" } },
  { id: "awlad-seif", code: "AWL", line: "cairo-alexandria", name: { en: "Awlad Seif", ar: "اولاد سيف" }, city: { en: "Awlad Seif", ar: "اولاد سيف" } },
  { id: "belbes", code: "BEL", line: "cairo-alexandria", name: { en: "Belbes", ar: "بلبيس" }, city: { en: "Belbes", ar: "بلبيس" } },
  { id: "inshas", code: "INS", line: "cairo-alexandria", name: { en: "Inshas", ar: "انشاص" }, city: { en: "Inshas", ar: "انشاص" } },
  { id: "mashtul", code: "MAS", line: "cairo-alexandria", name: { en: "Mashtul", ar: "مشتول" }, city: { en: "Mashtul", ar: "مشتول" } },
  { id: "asluji", code: "ASL", line: "cairo-alexandria", name: { en: "Asluji", ar: "العصلوجي" }, city: { en: "Asluji", ar: "العصلوجي" } },
  { id: "tall-rozan", code: "TAL", line: "cairo-alexandria", name: { en: "Tall Rozan", ar: "تل روزن" }, city: { en: "Tall Rozan", ar: "تل روزن" } },
  { id: "bir-imarah", code: "BIR", line: "cairo-alexandria", name: { en: "Bir Imarah", ar: "بير عمارة" }, city: { en: "Bir Imarah", ar: "بير عمارة" } },
  { id: "salamant", code: "SAL", line: "cairo-alexandria", name: { en: "Salamant", ar: "سلمنت" }, city: { en: "Salamant", ar: "سلمنت" } },
  { id: "monshaat-kiram", code: "MON", line: "cairo-alexandria", name: { en: "Monshaat Kiram", ar: "منشأة الكرام" }, city: { en: "Monshaat Kiram", ar: "منشأة الكرام" } },
  { id: "kafr-beni-helal", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Beni Helal", ar: "كفر بني هلال" }, city: { en: "Kafr Beni Helal", ar: "كفر بني هلال" } },
  { id: "nefrah", code: "NEF", line: "cairo-alexandria", name: { en: "Nefrah", ar: "نفرة" }, city: { en: "Nefrah", ar: "نفرة" } },
  { id: "sanhur", code: "SAN", line: "cairo-alexandria", name: { en: "Sanhur", ar: "سنهور" }, city: { en: "Sanhur", ar: "سنهور" } },
  { id: "hwariah", code: "HWA", line: "cairo-alexandria", name: { en: "Hwariah", ar: "الهوارية" }, city: { en: "Hwariah", ar: "الهوارية" } },
  { id: "khazan", code: "KHA", line: "cairo-alexandria", name: { en: "Khazan", ar: "الخزان" }, city: { en: "Khazan", ar: "الخزان" } },
  { id: "fath", code: "FAT", line: "cairo-alexandria", name: { en: "Fath", ar: "الفتح" }, city: { en: "Fath", ar: "الفتح" } },
  { id: "rahmaniah", code: "RAH", line: "cairo-alexandria", name: { en: "Rahmaniah", ar: "الرحمانية" }, city: { en: "Rahmaniah", ar: "الرحمانية" } },
  { id: "gmagmun", code: "GMA", line: "cairo-alexandria", name: { en: "Gmagmun", ar: "جماجمون" }, city: { en: "Gmagmun", ar: "جماجمون" } },
  { id: "madinah", code: "MAD", line: "cairo-alexandria", name: { en: "Madinah", ar: "المدينة" }, city: { en: "Madinah", ar: "المدينة" } },
  { id: "shbas", code: "SHB", line: "cairo-alexandria", name: { en: "Shbas", ar: "شباس" }, city: { en: "Shbas", ar: "شباس" } },
  { id: "kafr-gazayer", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Gazayer", ar: "كفر الجزاير" }, city: { en: "Kafr Gazayer", ar: "كفر الجزاير" } },
  { id: "bekatush", code: "BEK", line: "cairo-alexandria", name: { en: "Bekatush", ar: "البكاتوش" }, city: { en: "Bekatush", ar: "البكاتوش" } },
  { id: "qleen", code: "QLE", line: "delta", name: { en: "Qleen", ar: "قلين" }, city: { en: "Qleen", ar: "قلين" } },
  { id: "qleen-b", code: "QLE", line: "cairo-alexandria", name: { en: "Qleen B", ar: "قلين البلد" }, city: { en: "Qleen B", ar: "قلين البلد" } },
  { id: "ezbet-godah", code: "EZB", line: "cairo-alexandria", name: { en: "Ezbet Godah", ar: "عزبة جودة" }, city: { en: "Ezbet Godah", ar: "عزبة جودة" } },
  { id: "shin", code: "SHI", line: "cairo-alexandria", name: { en: "Shin", ar: "الشين" }, city: { en: "Shin", ar: "الشين" } },
  { id: "hwin", code: "HWI", line: "cairo-alexandria", name: { en: "Hwin", ar: "حوين" }, city: { en: "Hwin", ar: "حوين" } },
  { id: "qotur", code: "QOT", line: "cairo-alexandria", name: { en: "Qotur", ar: "قطور" }, city: { en: "Qotur", ar: "قطور" } },
  { id: "ibrahimiah", code: "IBR", line: "cairo-alexandria", name: { en: "Ibrahimiah", ar: "الابراهيمية" }, city: { en: "Ibrahimiah", ar: "الابراهيمية" } },
  { id: "ebshway", code: "EBS", line: "cairo-alexandria", name: { en: "Ebshway", ar: "ابشواي" }, city: { en: "Ebshway", ar: "ابشواي" } },
  { id: "segin", code: "SEG", line: "cairo-alexandria", name: { en: "Segin", ar: "سجين" }, city: { en: "Segin", ar: "سجين" } },
  { id: "henawi", code: "HEN", line: "delta", name: { en: "Henawi", ar: "الحناوي" }, city: { en: "Henawi", ar: "الحناوي" } },
  { id: "nashart", code: "NAS", line: "delta", name: { en: "Nashart", ar: "نشرت" }, city: { en: "Nashart", ar: "نشرت" } },
  { id: "monshaah-soghra", code: "MON", line: "delta", name: { en: "Monshaah Soghra", ar: "المنشأة الصغرى" }, city: { en: "Monshaah Soghra", ar: "المنشأة الصغرى" } },
  { id: "hamidiyyah", code: "HAM", line: "delta", name: { en: "Hamidiyyah", ar: "الحميدية" }, city: { en: "Hamidiyyah", ar: "الحميدية" } },
  { id: "mahallat-mousa", code: "MAH", line: "delta", name: { en: "Mahallat Mousa", ar: "محلة موسى" }, city: { en: "Mahallat Mousa", ar: "محلة موسى" } },
  { id: "rezqet-amay", code: "REZ", line: "delta", name: { en: "Rezqet Amay", ar: "رزقة أماي" }, city: { en: "Rezqet Amay", ar: "رزقة أماي" } },
  { id: "sakha", code: "SAK", line: "delta", name: { en: "Sakha", ar: "سخا" }, city: { en: "Sakha", ar: "سخا" } },
  { id: "murabian", code: "MUR", line: "delta", name: { en: "Murabian", ar: "المرابعين" }, city: { en: "Murabian", ar: "المرابعين" } },
  { id: "duqmayrah", code: "DUQ", line: "delta", name: { en: "Duqmayrah", ar: "دقميرة" }, city: { en: "Duqmayrah", ar: "دقميرة" } },
  { id: "salam", code: "SAL", line: "delta", name: { en: "Salam", ar: "السلام" }, city: { en: "Salam", ar: "السلام" } },
  { id: "sidi-ghazy", code: "SID", line: "delta", name: { en: "Sidi Ghazy", ar: "سيدي غازي" }, city: { en: "Sidi Ghazy", ar: "سيدي غازي" } },
  { id: "kom-taweel", code: "KOM", line: "delta", name: { en: "Kom Taweel", ar: "الكوم الطويل" }, city: { en: "Kom Taweel", ar: "الكوم الطويل" } },
  { id: "karykat", code: "KAR", line: "delta", name: { en: "Karykat", ar: "الكركات" }, city: { en: "Karykat", ar: "الكركات" } },
  { id: "kom-hajnah", code: "KOM", line: "delta", name: { en: "Kom Hajnah", ar: "كوم الحجنة" }, city: { en: "Kom Hajnah", ar: "كوم الحجنة" } },
  { id: "ibshan", code: "IBS", line: "delta", name: { en: "Ibshan", ar: "ابشان" }, city: { en: "Ibshan", ar: "ابشان" } },
  { id: "biyala", code: "BIY", line: "delta", name: { en: "Biyala", ar: "بيلا" }, city: { en: "Biyala", ar: "بيلا" } },
  { id: "kafr-garaydah", code: "KAF", line: "delta", name: { en: "Kafr Garaydah", ar: "كفر الجرايدة" }, city: { en: "Kafr Garaydah", ar: "كفر الجرايدة" } },
  { id: "buhut", code: "BUH", line: "delta", name: { en: "Buhut", ar: "بهوت" }, city: { en: "Buhut", ar: "بهوت" } },
  { id: "manshyt-badrawy", code: "MAN", line: "delta", name: { en: "Manshyt Badrawy", ar: "منشية البدراوي" }, city: { en: "Manshyt Badrawy", ar: "منشية البدراوي" } },
  { id: "belkas", code: "BEL", line: "delta", name: { en: "Belkas", ar: "بلقاس" }, city: { en: "Belkas", ar: "بلقاس" } },
  { id: "basandilah", code: "BAS", line: "delta", name: { en: "Basandilah", ar: "بسنديله" }, city: { en: "Basandilah", ar: "بسنديله" } },
  { id: "kafr-shennawy", code: "KAF", line: "delta", name: { en: "Kafr Shennawy", ar: "كفر الشناوي" }, city: { en: "Kafr Shennawy", ar: "كفر الشناوي" } },
  { id: "daljamun", code: "DAL", line: "cairo-alexandria", name: { en: "Daljamun", ar: "الدلجمون" }, city: { en: "Daljamun", ar: "الدلجمون" } },
  { id: "qasr-nasr-din", code: "QAS", line: "cairo-alexandria", name: { en: "Qasr Nasr Din", ar: "قصر نصر الدين" }, city: { en: "Qasr Nasr Din", ar: "قصر نصر الدين" } },
  { id: "kafr-mishlah", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Mishlah", ar: "كفر مشلة" }, city: { en: "Kafr Mishlah", ar: "كفر مشلة" } },
  { id: "mishlah", code: "MIS", line: "cairo-alexandria", name: { en: "Mishlah", ar: "مشلة" }, city: { en: "Mishlah", ar: "مشلة" } },
  { id: "izbat-hutaym", code: "IZB", line: "cairo-alexandria", name: { en: "Izbat Hutaym", ar: "عزبة الحطيم" }, city: { en: "Izbat Hutaym", ar: "عزبة الحطيم" } },
  { id: "tunub", code: "TUN", line: "cairo-alexandria", name: { en: "Tunub", ar: "طنوب" }, city: { en: "Tunub", ar: "طنوب" } },
  { id: "kom-mazin", code: "KOM", line: "cairo-alexandria", name: { en: "Kom Mazin", ar: "كوم مازن" }, city: { en: "Kom Mazin", ar: "كوم مازن" } },
  { id: "amrus", code: "AMR", line: "cairo-alexandria", name: { en: "Amrus", ar: "عمروس" }, city: { en: "Amrus", ar: "عمروس" } },
  { id: "beshtami", code: "BES", line: "cairo-alexandria", name: { en: "Beshtami", ar: "بشتامي" }, city: { en: "Beshtami", ar: "بشتامي" } },
  { id: "zawiyat-baqli", code: "ZAW", line: "cairo-alexandria", name: { en: "Zawiyat Baqli", ar: "زاوية البقلى" }, city: { en: "Zawiyat Baqli", ar: "زاوية البقلى" } },
  { id: "dinshaway", code: "DIN", line: "cairo-alexandria", name: { en: "Dinshaway", ar: "دنشواى" }, city: { en: "Dinshaway", ar: "دنشواى" } },
  { id: "shohada", code: "SHO", line: "cairo-alexandria", name: { en: "Shohada", ar: "الشهداء" }, city: { en: "Shohada", ar: "الشهداء" } },
  { id: "ashma", code: "ASH", line: "cairo-alexandria", name: { en: "Ashma", ar: "عشما" }, city: { en: "Ashma", ar: "عشما" } },
  { id: "iraqiyyah", code: "IRA", line: "cairo-alexandria", name: { en: "Iraqiyyah", ar: "العراقية" }, city: { en: "Iraqiyyah", ar: "العراقية" } },
  { id: "monshaat-sultan", code: "MON", line: "cairo-alexandria", name: { en: "Monshaat Sultan", ar: "منشأة سلطان" }, city: { en: "Monshaat Sultan", ar: "منشأة سلطان" } },
  { id: "sengerg", code: "SEN", line: "cairo-alexandria", name: { en: "Sengerg", ar: "سنجرج" }, city: { en: "Sengerg", ar: "سنجرج" } },
  { id: "kafr-bata", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Bata", ar: "كفر بطا" }, city: { en: "Kafr Bata", ar: "كفر بطا" } },
  { id: "istanha", code: "IST", line: "cairo-alexandria", name: { en: "Istanha", ar: "اسطنها" }, city: { en: "Istanha", ar: "اسطنها" } },
  { id: "mit-wusta", code: "MIT", line: "cairo-alexandria", name: { en: "Mit Wusta", ar: "ميت الواسطى" }, city: { en: "Mit Wusta", ar: "ميت الواسطى" } },
  { id: "subk-dahhak", code: "SUB", line: "cairo-alexandria", name: { en: "Subk Dahhak", ar: "سبك الضحاك" }, city: { en: "Subk Dahhak", ar: "سبك الضحاك" } },
  { id: "bagour", code: "BAG", line: "cairo-alexandria", name: { en: "Bagour", ar: "الباجور" }, city: { en: "Bagour", ar: "الباجور" } },
  { id: "jarawan", code: "JAR", line: "cairo-alexandria", name: { en: "Jarawan", ar: "جروان" }, city: { en: "Jarawan", ar: "جروان" } },
  { id: "kafr-shobra-zanji", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Shobra Zanji", ar: "كفر شبرا زنجي" }, city: { en: "Kafr Shobra Zanji", ar: "كفر شبرا زنجي" } },
  { id: "sirs-layyanah", code: "SIR", line: "cairo-alexandria", name: { en: "Sirs Layyanah", ar: "سرس الليان" }, city: { en: "Sirs Layyanah", ar: "سرس الليان" } },
  { id: "gharbaniat", code: "GHA", line: "north-coast", name: { en: "Gharbaniat", ar: "الغربانيات" }, city: { en: "Gharbaniat", ar: "الغربانيات" } },
  { id: "tafaro", code: "TAF", line: "north-coast", name: { en: "Tafaro", ar: "التفرع" }, city: { en: "Tafaro", ar: "التفرع" } },
  { id: "sidi-mergheb", code: "SID", line: "north-coast", name: { en: "Sidi Mergheb", ar: "سيدي مرغب" }, city: { en: "Sidi Mergheb", ar: "سيدي مرغب" } },
  { id: "metras", code: "MET", line: "north-coast", name: { en: "Metras", ar: "المتراس" }, city: { en: "Metras", ar: "المتراس" } },
  { id: "mowaslet-max", code: "MOW", line: "north-coast", name: { en: "Mowaslet Max", ar: "مواصلة المكس" }, city: { en: "Mowaslet Max", ar: "مواصلة المكس" } },
  { id: "ameed", code: "AME", line: "north-coast", name: { en: "Ameed", ar: "العميد" }, city: { en: "Ameed", ar: "العميد" } },
  { id: "gabbasat", code: "GAB", line: "north-coast", name: { en: "Gabbasat", ar: "الجباسات" }, city: { en: "Gabbasat", ar: "الجباسات" } },
  { id: "tal-issa", code: "TAL", line: "north-coast", name: { en: "Tal Issa", ar: "تل العيسى" }, city: { en: "Tal Issa", ar: "تل العيسى" } },
  { id: "ghazal", code: "GHA", line: "north-coast", name: { en: "Ghazal", ar: "غزال" }, city: { en: "Ghazal", ar: "غزال" } },
  { id: "sidi-hanosh", code: "SID", line: "north-coast", name: { en: "Sidi Hanosh", ar: "سيدي حنوش" }, city: { en: "Sidi Hanosh", ar: "سيدي حنوش" } },
  { id: "atnoh", code: "ATN", line: "north-coast", name: { en: "Atnoh", ar: "اطنوح" }, city: { en: "Atnoh", ar: "اطنوح" } },
  { id: "fardyah", code: "FAR", line: "north-coast", name: { en: "Fardyah", ar: "الفردية" }, city: { en: "Fardyah", ar: "الفردية" } },
  { id: "sidi-shbeeb", code: "SID", line: "north-coast", name: { en: "Sidi Shbeeb", ar: "سيدي شبيب" }, city: { en: "Sidi Shbeeb", ar: "سيدي شبيب" } },
  { id: "werdan", code: "WER", line: "cairo-alexandria", name: { en: "Werdan", ar: "وردان" }, city: { en: "Werdan", ar: "وردان" } },
  { id: "beni-salamah", code: "BEN", line: "upper-egypt", name: { en: "Beni Salamah", ar: "بني سلامة" }, city: { en: "Beni Salamah", ar: "بني سلامة" } },
  { id: "khatatbah", code: "KHA", line: "cairo-alexandria", name: { en: "Khatatbah", ar: "الخطاطبة" }, city: { en: "Khatatbah", ar: "الخطاطبة" } },
  { id: "akhmas", code: "AKH", line: "upper-egypt", name: { en: "Akhmas", ar: "الاخماس" }, city: { en: "Akhmas", ar: "الاخماس" } },
  { id: "tarranah", code: "TAR", line: "upper-egypt", name: { en: "Tarranah", ar: "الطرانة" }, city: { en: "Tarranah", ar: "الطرانة" } },
  { id: "kafr-dawoud", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Dawoud", ar: "كفر داود" }, city: { en: "Kafr Dawoud", ar: "كفر داود" } },
  { id: "birijat", code: "BIR", line: "upper-egypt", name: { en: "Birijat", ar: "البريجات" }, city: { en: "Birijat", ar: "البريجات" } },
  { id: "modiriyat-tahrir", code: "MOD", line: "cairo-alexandria", name: { en: "Modiriyat Tahrir", ar: "مديرية التحرير" }, city: { en: "Modiriyat Tahrir", ar: "مديرية التحرير" } },
  { id: "abo-khawi", code: "ABO", line: "cairo-alexandria", name: { en: "Abo Khawi", ar: "ابو الخاوي" }, city: { en: "Abo Khawi", ar: "ابو الخاوي" } },
  { id: "tairyyah", code: "TAI", line: "cairo-alexandria", name: { en: "Tairyyah", ar: "الطيرية" }, city: { en: "Tairyyah", ar: "الطيرية" } },
  { id: "tairyyah-b", code: "TAI", line: "cairo-alexandria", name: { en: "Tairyyah B", ar: "الطيرية البلد" }, city: { en: "Tairyyah B", ar: "الطيرية البلد" } },
  { id: "ethaad", code: "ETH", line: "cairo-alexandria", name: { en: "Ethaad", ar: "الاتحاد" }, city: { en: "Ethaad", ar: "الاتحاد" } },
  { id: "monshaat-abo-rayyah", code: "MON", line: "cairo-alexandria", name: { en: "Monshaat Abo Rayyah", ar: "منشاة ابو رية" }, city: { en: "Monshaat Abo Rayyah", ar: "منشاة ابو رية" } },
  { id: "waqid", code: "WAQ", line: "cairo-alexandria", name: { en: "Waqid", ar: "واقد" }, city: { en: "Waqid", ar: "واقد" } },
  { id: "kafr-bulin", code: "KAF", line: "cairo-alexandria", name: { en: "Kafr Bulin", ar: "كفر بولين" }, city: { en: "Kafr Bulin", ar: "كفر بولين" } },
  { id: "kom-hamada", code: "KOM", line: "cairo-alexandria", name: { en: "Kom Hamada", ar: "كوم حمادة" }, city: { en: "Kom Hamada", ar: "كوم حمادة" } },
  { id: "naqidi", code: "NAQ", line: "cairo-alexandria", name: { en: "Naqidi", ar: "النقيدي" }, city: { en: "Naqidi", ar: "النقيدي" } },
  { id: "saft-inab", code: "SAF", line: "cairo-alexandria", name: { en: "Saft Inab", ar: "صفط العنب" }, city: { en: "Saft Inab", ar: "صفط العنب" } },
  { id: "qilishan", code: "QIL", line: "cairo-alexandria", name: { en: "Qilishan", ar: "قليشان" }, city: { en: "Qilishan", ar: "قليشان" } },
  { id: "hadrah", code: "HAD", line: "cairo-alexandria", name: { en: "Hadrah", ar: "الحضرة" }, city: { en: "Hadrah", ar: "الحضرة" } },
  { id: "bashtil-b", code: "BAS", line: "cairo-alexandria", name: { en: "Bashtil B", ar: "بشتيل البلد" }, city: { en: "Bashtil B", ar: "بشتيل البلد" } },
  { id: "ossim", code: "OSS", line: "upper-egypt", name: { en: "Ossim", ar: "اوسيم" }, city: { en: "Ossim", ar: "اوسيم" } },
  { id: "manashi", code: "MAN", line: "upper-egypt", name: { en: "Manashi", ar: "المناشي" }, city: { en: "Manashi", ar: "المناشي" } },
  { id: "niklah", code: "NIK", line: "upper-egypt", name: { en: "Niklah", ar: "نكلا" }, city: { en: "Niklah", ar: "نكلا" } },
  { id: "birqash", code: "BIR", line: "upper-egypt", name: { en: "Birqash", ar: "برقاش" }, city: { en: "Birqash", ar: "برقاش" } },
  { id: "abo-ghaleb", code: "ABO", line: "upper-egypt", name: { en: "Abo Ghaleb", ar: "ابو غالب" }, city: { en: "Abo Ghaleb", ar: "ابو غالب" } },
  { id: "gezira-wastanih", code: "GEZ", line: "upper-egypt", name: { en: "Gezira wastanih", ar: "الجزيرة الوسطانية" }, city: { en: "Gezira wastanih", ar: "الجزيرة الوسطانية" } },
  { id: "qata-b", code: "QAT", line: "upper-egypt", name: { en: "Qata B", ar: "القطا البلد" }, city: { en: "Qata B", ar: "القطا البلد" } },
  { id: "qata", code: "QAT", line: "upper-egypt", name: { en: "Qata", ar: "القطا" }, city: { en: "Qata", ar: "القطا" } },
  { id: "zat-kom", code: "ZAT", line: "upper-egypt", name: { en: "Zat Kom", ar: "ذات الكوم" }, city: { en: "Zat Kom", ar: "ذات الكوم" } },
  { id: "gelatmah", code: "GEL", line: "upper-egypt", name: { en: "Gelatmah", ar: "الجلاتمة" }, city: { en: "Gelatmah", ar: "الجلاتمة" } },
  { id: "bartas", code: "BAR", line: "upper-egypt", name: { en: "Bartas", ar: "برطس" }, city: { en: "Bartas", ar: "برطس" } },
  { id: "kom-ahmar", code: "KOM", line: "cairo-alexandria", name: { en: "Kom Ahmar", ar: "الكوم الاحمر" }, city: { en: "Kom Ahmar", ar: "الكوم الاحمر" } },
  { id: "azhar-university", code: "AZH", line: "upper-egypt", name: { en: "Azhar University", ar: "جامعة الأزهر" }, city: { en: "Azhar University", ar: "جامعة الأزهر" } },
  { id: "beni-qorah", code: "BEN", line: "upper-egypt", name: { en: "Beni Qorah", ar: "بني قره" }, city: { en: "Beni Qorah", ar: "بني قره" } },
  { id: "awlad-ilyas", code: "AWL", line: "upper-egypt", name: { en: "Awlad Ilyas", ar: "اولاد الياس" }, city: { en: "Awlad Ilyas", ar: "اولاد الياس" } },
  { id: "shatb", code: "SHA", line: "upper-egypt", name: { en: "Shatb", ar: "شطب" }, city: { en: "Shatb", ar: "شطب" } },
  { id: "mutiah", code: "MUT", line: "upper-egypt", name: { en: "Mutiah", ar: "المطيعة" }, city: { en: "Mutiah", ar: "المطيعة" } },
  { id: "baqur", code: "BAQ", line: "upper-egypt", name: { en: "Baqur", ar: "باقور" }, city: { en: "Baqur", ar: "باقور" } },
  { id: "nekhaylah", code: "NEK", line: "upper-egypt", name: { en: "Nekhaylah", ar: "النخيلة" }, city: { en: "Nekhaylah", ar: "النخيلة" } },
  { id: "mishta", code: "MIS", line: "upper-egypt", name: { en: "Mishta", ar: "مشطا" }, city: { en: "Mishta", ar: "مشطا" } },
  { id: "shatourah", code: "SHA", line: "upper-egypt", name: { en: "Shatourah", ar: "شطورة" }, city: { en: "Shatourah", ar: "شطورة" } },
  { id: "banja", code: "BAN", line: "upper-egypt", name: { en: "Banja", ar: "بنجا" }, city: { en: "Banja", ar: "بنجا" } },
  { id: "sawamaah", code: "SAW", line: "upper-egypt", name: { en: "Sawamaah", ar: "الصوامعة" }, city: { en: "Sawamaah", ar: "الصوامعة" } },
  { id: "sayh", code: "SAY", line: "upper-egypt", name: { en: "Sayh", ar: "السايح" }, city: { en: "Sayh", ar: "السايح" } },
  { id: "shandawil-b", code: "SHA", line: "upper-egypt", name: { en: "Shandawil B", ar: "شندويل البلد" }, city: { en: "Shandawil B", ar: "شندويل البلد" } },
  { id: "jazirat-shandawil", code: "JAZ", line: "upper-egypt", name: { en: "Jazirat Shandawil", ar: "جزيرة شندويل" }, city: { en: "Jazirat Shandawil", ar: "جزيرة شندويل" } },
  { id: "balasfurah", code: "BAL", line: "upper-egypt", name: { en: "Balasfurah", ar: "بلصفورة" }, city: { en: "Balasfurah", ar: "بلصفورة" } },
  { id: "isawiyyah", code: "ISA", line: "upper-egypt", name: { en: "Isawiyyah", ar: "العيساوية" }, city: { en: "Isawiyyah", ar: "العيساوية" } },
  { id: "ahaywah", code: "AHA", line: "upper-egypt", name: { en: "Ahaywah", ar: "الأحايوه" }, city: { en: "Ahaywah", ar: "الأحايوه" } },
  { id: "bindar", code: "BIN", line: "upper-egypt", name: { en: "Bindar", ar: "البندار" }, city: { en: "Bindar", ar: "البندار" } },
  { id: "mzata-west", code: "MZA", line: "upper-egypt", name: { en: "Mzata west", ar: "مزاتا غرب" }, city: { en: "Mzata west", ar: "مزاتا غرب" } },
  { id: "sahel-q", code: "SAH", line: "upper-egypt", name: { en: "Sahel Q", ar: "الساحل ق" }, city: { en: "Sahel Q", ar: "الساحل ق" } },
  { id: "beni-hamil", code: "BEN", line: "upper-egypt", name: { en: "Beni Hamil", ar: "بني حميل" }, city: { en: "Beni Hamil", ar: "بني حميل" } },
  { id: "samhud", code: "SAM", line: "upper-egypt", name: { en: "Samhud", ar: "سمهود" }, city: { en: "Samhud", ar: "سمهود" } },
  { id: "rufaa", code: "RUF", line: "upper-egypt", name: { en: "Rufaa", ar: "رفاعة" }, city: { en: "Rufaa", ar: "رفاعة" } },
  { id: "bahjurah", code: "BAH", line: "upper-egypt", name: { en: "Bahjurah", ar: "بهجورة" }, city: { en: "Bahjurah", ar: "بهجورة" } },
  { id: "fuzah", code: "FUZ", line: "upper-egypt", name: { en: "Fuzah", ar: "الفوزة" }, city: { en: "Fuzah", ar: "الفوزة" } },
  { id: "tunab", code: "TUN", line: "upper-egypt", name: { en: "Tunab", ar: "الطوناب" }, city: { en: "Tunab", ar: "الطوناب" } },
  { id: "siraj", code: "SIR", line: "upper-egypt", name: { en: "Siraj", ar: "السراج" }, city: { en: "Siraj", ar: "السراج" } },
  { id: "gaafar-sadik", code: "GAA", line: "upper-egypt", name: { en: "Gaafar Sadik", ar: "جعفر الصادق" }, city: { en: "Gaafar Sadik", ar: "جعفر الصادق" } },
  { id: "sayid-said", code: "SAY", line: "upper-egypt", name: { en: "sayid Said", ar: "السيد سعيد" }, city: { en: "sayid Said", ar: "السيد سعيد" } },
  { id: "gebel-silsila", code: "GEB", line: "upper-egypt", name: { en: "Gebel Silsila", ar: "جبل السلسلة" }, city: { en: "Gebel Silsila", ar: "جبل السلسلة" } },
  { id: "raghama", code: "RAG", line: "upper-egypt", name: { en: "Raghama", ar: "الرغامة" }, city: { en: "Raghama", ar: "الرغامة" } },
  { id: "shatb-b", code: "SHA", line: "upper-egypt", name: { en: "Shatb B", ar: "الشطب البلد" }, city: { en: "Shatb B", ar: "الشطب البلد" } },
  { id: "salam-aneibah", code: "SAL", line: "upper-egypt", name: { en: "Salam Aneibah", ar: "السلام النوبية" }, city: { en: "Salam Aneibah", ar: "السلام النوبية" } },
  { id: "retaj", code: "RET", line: "upper-egypt", name: { en: "Retaj", ar: "الرتاج" }, city: { en: "Retaj", ar: "الرتاج" } },
  { id: "jaafrah", code: "JAA", line: "upper-egypt", name: { en: "Jaafrah", ar: "الجعافرة" }, city: { en: "Jaafrah", ar: "الجعافرة" } },
  { id: "aaqab", code: "AAQ", line: "upper-egypt", name: { en: "Aaqab", ar: "الاعقاب" }, city: { en: "Aaqab", ar: "الاعقاب" } },
  { id: "aaqab-q", code: "AAQ", line: "upper-egypt", name: { en: "Aaqab Q", ar: "الاعقاب ق" }, city: { en: "Aaqab Q", ar: "الاعقاب ق" } },
  { id: "khttarah", code: "KHT", line: "upper-egypt", name: { en: "Khttarah", ar: "الخطارة" }, city: { en: "Khttarah", ar: "الخطارة" } },
  { id: "shadedh", code: "SHA", line: "upper-egypt", name: { en: "Shadedh", ar: "الشديدة" }, city: { en: "Shadedh", ar: "الشديدة" } },
  { id: "abo-resh-q", code: "ABO", line: "upper-egypt", name: { en: "Abo Resh Q", ar: "ابو الريش ق" }, city: { en: "Abo Resh Q", ar: "ابو الريش ق" } },
  { id: "atwani", code: "ATW", line: "upper-egypt", name: { en: "Atwani", ar: "العطواني" }, city: { en: "Atwani", ar: "العطواني" } },
  { id: "dawamaria", code: "DAW", line: "upper-egypt", name: { en: "Dawamaria", ar: "الدومارية" }, city: { en: "Dawamaria", ar: "الدومارية" } },
  { id: "kilh", code: "KIL", line: "upper-egypt", name: { en: "Kilh", ar: "الكلح" }, city: { en: "Kilh", ar: "الكلح" } },
  { id: "phosphate-n", code: "PHO", line: "upper-egypt", name: { en: "Phosphate N", ar: "الفوسفات ج" }, city: { en: "Phosphate N", ar: "الفوسفات ج" } },
  { id: "khoy-n", code: "KHO", line: "upper-egypt", name: { en: "Khoy N", ar: "الخوي ج" }, city: { en: "Khoy N", ar: "الخوي ج" } },
  { id: "gazirat-rageh", code: "GAZ", line: "upper-egypt", name: { en: "Gazirat Rageh", ar: "جزيرة راجح" }, city: { en: "Gazirat Rageh", ar: "جزيرة راجح" } },
  { id: "kelabeyah", code: "KEL", line: "upper-egypt", name: { en: "Kelabeyah", ar: "الكلابية" }, city: { en: "Kelabeyah", ar: "الكلابية" } },
  { id: "deir", code: "DEI", line: "upper-egypt", name: { en: "Deir", ar: "الدير" }, city: { en: "Deir", ar: "الدير" } },
  { id: "mataenah", code: "MAT", line: "upper-egypt", name: { en: "Mataenah", ar: "المطاعنة" }, city: { en: "Mataenah", ar: "المطاعنة" } },
  { id: "nagaa-abo-said", code: "NAG", line: "upper-egypt", name: { en: "Nagaa Abo Said", ar: "نجع ابو سعيد" }, city: { en: "Nagaa Abo Said", ar: "نجع ابو سعيد" } },
  { id: "maelah", code: "MAE", line: "upper-egypt", name: { en: "Maelah", ar: "المعلة" }, city: { en: "Maelah", ar: "المعلة" } },
  { id: "shaghab", code: "SHA", line: "upper-egypt", name: { en: "Shaghab", ar: "الشغب" }, city: { en: "Shaghab", ar: "الشغب" } },
  { id: "idisat", code: "IDI", line: "upper-egypt", name: { en: "Idisat", ar: "العديسات" }, city: { en: "Idisat", ar: "العديسات" } },
  { id: "nagaa-gossor", code: "NAG", line: "upper-egypt", name: { en: "Nagaa Gossor", ar: "نجع الجسور" }, city: { en: "Nagaa Gossor", ar: "نجع الجسور" } },
  { id: "toud", code: "TOU", line: "upper-egypt", name: { en: "Toud", ar: "الطود" }, city: { en: "Toud", ar: "الطود" } },
  { id: "wehdaa", code: "WEH", line: "upper-egypt", name: { en: "Wehdaa", ar: "الوحدة" }, city: { en: "Wehdaa", ar: "الوحدة" } },
  { id: "boghdady", code: "BOG", line: "upper-egypt", name: { en: "Boghdady", ar: "البغدادي" }, city: { en: "Boghdady", ar: "البغدادي" } },
  { id: "radwania", code: "RAD", line: "upper-egypt", name: { en: "Radwania", ar: "الرضوانية" }, city: { en: "Radwania", ar: "الرضوانية" } },
  { id: "salmiyyah-q", code: "SAL", line: "upper-egypt", name: { en: "Salmiyyah Q", ar: "السلمية ق" }, city: { en: "Salmiyyah Q", ar: "السلمية ق" } },
  { id: "rahmaneyah-q", code: "RAH", line: "upper-egypt", name: { en: "Rahmaneyah Q", ar: "الرحمانية ق" }, city: { en: "Rahmaneyah Q", ar: "الرحمانية ق" } },
  { id: "baseineyah", code: "BAS", line: "upper-egypt", name: { en: "Baseineyah", ar: "الياسينية" }, city: { en: "Baseineyah", ar: "الياسينية" } },
  { id: "faw", code: "FAW", line: "upper-egypt", name: { en: "Faw", ar: "فاو" }, city: { en: "Faw", ar: "فاو" } },
  { id: "marashdah", code: "MAR", line: "upper-egypt", name: { en: "Marashdah", ar: "المراشدة" }, city: { en: "Marashdah", ar: "المراشدة" } },
  { id: "samta-q", code: "SAM", line: "upper-egypt", name: { en: "Samta Q", ar: "السمطا" }, city: { en: "Samta Q", ar: "السمطا" } },
  { id: "awlad-amr", code: "AWL", line: "upper-egypt", name: { en: "Awlad Amr", ar: "اولاد عمرو" }, city: { en: "Awlad Amr", ar: "اولاد عمرو" } },
  { id: "qinawiyyah", code: "QIN", line: "upper-egypt", name: { en: "Qinawiyyah", ar: "القناوية" }, city: { en: "Qinawiyyah", ar: "القناوية" } },
  { id: "makhadmah", code: "MAK", line: "upper-egypt", name: { en: "Makhadmah", ar: "المخادمة" }, city: { en: "Makhadmah", ar: "المخادمة" } },
  { id: "jiziriyyah", code: "JIZ", line: "upper-egypt", name: { en: "Jiziriyyah", ar: "الجزيرية" }, city: { en: "Jiziriyyah", ar: "الجزيرية" } },
  { id: "ashraf-qibliyyah", code: "ASH", line: "upper-egypt", name: { en: "Ashraf Qibliyyah", ar: "الاشراف ق" }, city: { en: "Ashraf Qibliyyah", ar: "الاشراف ق" } },
  { id: "ashraf", code: "ASH", line: "upper-egypt", name: { en: "Ashraf", ar: "الاشراف" }, city: { en: "Ashraf", ar: "الاشراف" } },
  { id: "abnoud", code: "ABN", line: "upper-egypt", name: { en: "Abnoud", ar: "ابنود" }, city: { en: "Abnoud", ar: "ابنود" } },
  { id: "barahmah", code: "BAR", line: "upper-egypt", name: { en: "Barahmah", ar: "البراهمة" }, city: { en: "Barahmah", ar: "البراهمة" } },
  { id: "karateyah", code: "KAR", line: "upper-egypt", name: { en: "Karateyah", ar: "الكراتية" }, city: { en: "Karateyah", ar: "الكراتية" } },
  { id: "sheikh-amer", code: "SHE", line: "upper-egypt", name: { en: "Sheikh Amer", ar: "الشيخ عامر" }, city: { en: "Sheikh Amer", ar: "الشيخ عامر" } },
  { id: "shanhoria", code: "SHA", line: "upper-egypt", name: { en: "Shanhoria", ar: "الشنهورية" }, city: { en: "Shanhoria", ar: "الشنهورية" } },
  { id: "ayshah", code: "AYS", line: "upper-egypt", name: { en: "Ayshah", ar: "العيايشة" }, city: { en: "Ayshah", ar: "العيايشة" } },
  { id: "khozam", code: "KHO", line: "upper-egypt", name: { en: "Khozam", ar: "خزام" }, city: { en: "Khozam", ar: "خزام" } },
  { id: "zayniyyah", code: "ZAY", line: "upper-egypt", name: { en: "Zayniyyah", ar: "الزينية" }, city: { en: "Zayniyyah", ar: "الزينية" } },
  { id: "karnak", code: "KAR", line: "upper-egypt", name: { en: "Karnak", ar: "الكرنك" }, city: { en: "Karnak", ar: "الكرنك" } },
  { id: "mamurah", code: "MAM", line: "delta", name: { en: "Mamurah", ar: "المعمورة" }, city: { en: "Mamurah", ar: "المعمورة" } },
  { id: "naval-college", code: "NAV", line: "delta", name: { en: "Naval college", ar: "الكلية البحرية" }, city: { en: "Naval college", ar: "الكلية البحرية" } },
  { id: "tabya", code: "TAB", line: "delta", name: { en: "Tabya", ar: "الطابية" }, city: { en: "Tabya", ar: "الطابية" } },
  { id: "abo-qir-fertilizer", code: "ABO", line: "delta", name: { en: "Abo Qir Fertilizer", ar: "سماد ابو قير" }, city: { en: "Abo Qir Fertilizer", ar: "سماد ابو قير" } },
  { id: "tarh", code: "TAR", line: "delta", name: { en: "Tarh", ar: "الطرح" }, city: { en: "Tarh", ar: "الطرح" } },
  { id: "maadeyah", code: "MAA", line: "delta", name: { en: "Maadeyah", ar: "المعدية" }, city: { en: "Maadeyah", ar: "المعدية" } },
  { id: "abaadiah", code: "ABA", line: "delta", name: { en: "Abaadiah", ar: "الابعدية" }, city: { en: "Abaadiah", ar: "الابعدية" } },
  { id: "lago-idku", code: "LAG", line: "delta", name: { en: "Lago Idku", ar: "بحيرة ادكو" }, city: { en: "Lago Idku", ar: "بحيرة ادكو" } },
  { id: "damietty", code: "DAM", line: "delta", name: { en: "Damietty", ar: "الدمياطي" }, city: { en: "Damietty", ar: "الدمياطي" } },
  { id: "idku", code: "IDK", line: "delta", name: { en: "Idku", ar: "ادكو" }, city: { en: "Idku", ar: "ادكو" } },
  { id: "miah", code: "MIA", line: "delta", name: { en: "Miah", ar: "مياح" }, city: { en: "Miah", ar: "مياح" } },
  { id: "manshyt-amel", code: "MAN", line: "delta", name: { en: "Manshyt Amel", ar: "منشية الأمل" }, city: { en: "Manshyt Amel", ar: "منشية الأمل" } },
  { id: "busayli", code: "BUS", line: "delta", name: { en: "Busayli", ar: "البصيلي" }, city: { en: "Busayli", ar: "البصيلي" } },
  { id: "mansour-basha", code: "MAN", line: "cairo-alexandria", name: { en: "Mansour Basha", ar: "منصور باشا" }, city: { en: "Mansour Basha", ar: "منصور باشا" } },
  { id: "ismail-sedky", code: "ISM", line: "cairo-alexandria", name: { en: "Ismail Sedky", ar: "اسماعيل صدقي" }, city: { en: "Ismail Sedky", ar: "اسماعيل صدقي" } },
  { id: "saad-zaghloul", code: "SAA", line: "cairo-alexandria", name: { en: "Saad Zaghloul", ar: "سعد زغلول" }, city: { en: "Saad Zaghloul", ar: "سعد زغلول" } },
  { id: "mit-harun", code: "MIT", line: "cairo-alexandria", name: { en: "Mit Harun", ar: "ميت الحارون" }, city: { en: "Mit Harun", ar: "ميت الحارون" } },
  { id: "tafahna-azab", code: "TAF", line: "cairo-alexandria", name: { en: "Tafahna Azab", ar: "تفهنا العزب" }, city: { en: "Tafahna Azab", ar: "تفهنا العزب" } },
  { id: "shobra-bukhum", code: "SHO", line: "cairo-alexandria", name: { en: "Shobra Bukhum", ar: "شبرا بخوم" }, city: { en: "Shobra Bukhum", ar: "شبرا بخوم" } },
  { id: "baqsa", code: "BAQ", line: "cairo-alexandria", name: { en: "Baqsa", ar: "بقسا" }, city: { en: "Baqsa", ar: "بقسا" } },
  { id: "mit-barh", code: "MIT", line: "cairo-alexandria", name: { en: "Mit Barh", ar: "ميت بره" }, city: { en: "Mit Barh", ar: "ميت بره" } },
  { id: "mit-hufiyyin", code: "MIT", line: "cairo-alexandria", name: { en: "Mit Hufiyyin", ar: "ميت الحوفيين" }, city: { en: "Mit Hufiyyin", ar: "ميت الحوفيين" } },
  { id: "damallu", code: "DAM", line: "cairo-alexandria", name: { en: "Damallu", ar: "دملو" }, city: { en: "Damallu", ar: "دملو" } },
  { id: "warwarah", code: "WAR", line: "cairo-alexandria", name: { en: "Warwarah", ar: "ورورة" }, city: { en: "Warwarah", ar: "ورورة" } },
  { id: "ashmant", code: "ASH", line: "upper-egypt", name: { en: "Ashmant", ar: "اشمنت" }, city: { en: "Ashmant", ar: "اشمنت" } },
  { id: "suds", code: "SUD", line: "upper-egypt", name: { en: "Suds", ar: "سدس" }, city: { en: "Suds", ar: "سدس" } },
  { id: "taha-bishah", code: "TAH", line: "upper-egypt", name: { en: "Taha Bishah", ar: "طحا البيشة" }, city: { en: "Taha Bishah", ar: "طحا البيشة" } },
  { id: "tansa", code: "TAN", line: "upper-egypt", name: { en: "Tansa", ar: "طنسا" }, city: { en: "Tansa", ar: "طنسا" } },
  { id: "zaytoun-q", code: "ZAY", line: "upper-egypt", name: { en: "Zaytoun Q", ar: "الزيتون ق" }, city: { en: "Zaytoun Q", ar: "الزيتون ق" } },
  { id: "maymun", code: "MAY", line: "upper-egypt", name: { en: "Maymun", ar: "الميمون" }, city: { en: "Maymun", ar: "الميمون" } },
  { id: "beni-hidayr", code: "BEN", line: "upper-egypt", name: { en: "Beni Hidayr", ar: "بني حدير" }, city: { en: "Beni Hidayr", ar: "بني حدير" } },
  { id: "25-jan", code: "25-", line: "cairo-alexandria", name: { en: "25 Jan", ar: "25 يناير" }, city: { en: "25 Jan", ar: "25 يناير" } },
  { id: "burj-arab-n", code: "BUR", line: "cairo-alexandria", name: { en: "Burj Arab N", ar: "برج العرب ج" }, city: { en: "Burj Arab N", ar: "برج العرب ج" } },
  { id: "agrod-n", code: "AGR", line: "canal", name: { en: "Agrod N", ar: "العجرود ج" }, city: { en: "Agrod N", ar: "العجرود ج" } },
  { id: "jabal-obaid", code: "JAB", line: "canal", name: { en: "Jabal Obaid", ar: "جبل عوبيد" }, city: { en: "Jabal Obaid", ar: "جبل عوبيد" } },
  { id: "jabal-jufra", code: "JAB", line: "canal", name: { en: "Jabal Jufra", ar: "جبل الجفرة" }, city: { en: "Jabal Jufra", ar: "جبل الجفرة" } },
  { id: "wadi-sail", code: "WAD", line: "canal", name: { en: "Wadi Sail", ar: "وادي السيل" }, city: { en: "Wadi Sail", ar: "وادي السيل" } },
  { id: "robaikey", code: "ROB", line: "canal", name: { en: "Robaikey", ar: "الربيكي" }, city: { en: "Robaikey", ar: "الربيكي" } },
  { id: "badr", code: "BAD", line: "canal", name: { en: "Badr", ar: "بدر" }, city: { en: "Badr", ar: "بدر" } },
  { id: "shorouk", code: "SHO", line: "canal", name: { en: "Shorouk", ar: "الشروق" }, city: { en: "Shorouk", ar: "الشروق" } },
  { id: "darb-haj", code: "DAR", line: "canal", name: { en: "Darb Haj", ar: "درب الحاج" }, city: { en: "Darb Haj", ar: "درب الحاج" } },
  { id: "obour", code: "OBO", line: "canal", name: { en: "Obour", ar: "العبور" }, city: { en: "Obour", ar: "العبور" } },
];