/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125SearchRouteImport } from './routes/{-$locale}/search'
import { Route as Char123LocaleChar125PaymentRouteImport } from './routes/{-$locale}/payment'
import { Route as Char123LocaleChar125PassengerRouteImport } from './routes/{-$locale}/passenger'
import { Route as Char123LocaleChar125NewsRouteImport } from './routes/{-$locale}/news'
import { Route as Char123LocaleChar125InvestorsRouteImport } from './routes/{-$locale}/investors'
import { Route as Char123LocaleChar125HelpRouteImport } from './routes/{-$locale}/help'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125ConfirmationRouteImport } from './routes/{-$locale}/confirmation'
import { Route as Char123LocaleChar125ClassRouteImport } from './routes/{-$locale}/class'
import { Route as Char123LocaleChar125CareersRouteImport } from './routes/{-$locale}/careers'
import { Route as Char123LocaleChar125AuthRouteImport } from './routes/{-$locale}/auth'
import { Route as Char123LocaleChar125AccessibilityRouteImport } from './routes/{-$locale}/accessibility'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125AuthenticatedRouteRouteImport } from './routes/{-$locale}/_authenticated/route'
import { Route as Char123LocaleChar125TimetableIndexRouteImport } from './routes/{-$locale}/timetable/index'
import { Route as Char123LocaleChar125StationsIndexRouteImport } from './routes/{-$locale}/stations/index'
import { Route as Char123LocaleChar125TravelInfoSafetyRouteImport } from './routes/{-$locale}/travel-info/safety'
import { Route as Char123LocaleChar125TravelInfoLuggageRouteImport } from './routes/{-$locale}/travel-info/luggage'
import { Route as Char123LocaleChar125TravelInfoLostPropertyRouteImport } from './routes/{-$locale}/travel-info/lost-property'
import { Route as Char123LocaleChar125TimetableLiveRouteImport } from './routes/{-$locale}/timetable/live'
import { Route as Char123LocaleChar125TimetableAlertsRouteImport } from './routes/{-$locale}/timetable/alerts'
import { Route as Char123LocaleChar125TicketsPassesRouteImport } from './routes/{-$locale}/tickets/passes'
import { Route as Char123LocaleChar125TicketsFaresRouteImport } from './routes/{-$locale}/tickets/fares'
import { Route as Char123LocaleChar125TicketsDiscountsRouteImport } from './routes/{-$locale}/tickets/discounts'
import { Route as Char123LocaleChar125StationsIdRouteImport } from './routes/{-$locale}/stations/$id'
import { Route as Char123LocaleChar125NetworkMapRouteImport } from './routes/{-$locale}/network/map'
import { Route as Char123LocaleChar125NetworkLinesRouteImport } from './routes/{-$locale}/network/lines'
import { Route as Char123LocaleChar125LegalTermsRouteImport } from './routes/{-$locale}/legal/terms'
import { Route as Char123LocaleChar125LegalRefundsRouteImport } from './routes/{-$locale}/legal/refunds'
import { Route as Char123LocaleChar125LegalPrivacyRouteImport } from './routes/{-$locale}/legal/privacy'
import { Route as Char123LocaleChar125LegalCookiesRouteImport } from './routes/{-$locale}/legal/cookies'
import { Route as Char123LocaleChar125AuthenticatedAccountIndexRouteImport } from './routes/{-$locale}/_authenticated/account/index'
import { Route as Char123LocaleChar125AuthenticatedAccountTravellersRouteImport } from './routes/{-$locale}/_authenticated/account/travellers'
import { Route as Char123LocaleChar125AuthenticatedAccountPaymentRouteImport } from './routes/{-$locale}/_authenticated/account/payment'
import { Route as Char123LocaleChar125AuthenticatedAccountNotificationsRouteImport } from './routes/{-$locale}/_authenticated/account/notifications'
import { Route as Char123LocaleChar125AuthenticatedAccountJourneysRouteImport } from './routes/{-$locale}/_authenticated/account/journeys'
import { Route as Char123LocaleChar125AuthenticatedAccountBookingsRouteImport } from './routes/{-$locale}/_authenticated/account/bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SearchRoute =
  Char123LocaleChar125SearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PaymentRoute =
  Char123LocaleChar125PaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PassengerRoute =
  Char123LocaleChar125PassengerRouteImport.update({
    id: '/passenger',
    path: '/passenger',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125NewsRoute =
  Char123LocaleChar125NewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125InvestorsRoute =
  Char123LocaleChar125InvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125HelpRoute =
  Char123LocaleChar125HelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ConfirmationRoute =
  Char123LocaleChar125ConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125ClassRoute =
  Char123LocaleChar125ClassRouteImport.update({
    id: '/class',
    path: '/class',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CareersRoute =
  Char123LocaleChar125CareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthRoute =
  Char123LocaleChar125AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AccessibilityRoute =
  Char123LocaleChar125AccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedRouteRoute =
  Char123LocaleChar125AuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TimetableIndexRoute =
  Char123LocaleChar125TimetableIndexRouteImport.update({
    id: '/timetable/',
    path: '/timetable/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125StationsIndexRoute =
  Char123LocaleChar125StationsIndexRouteImport.update({
    id: '/stations/',
    path: '/stations/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TravelInfoSafetyRoute =
  Char123LocaleChar125TravelInfoSafetyRouteImport.update({
    id: '/travel-info/safety',
    path: '/travel-info/safety',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TravelInfoLuggageRoute =
  Char123LocaleChar125TravelInfoLuggageRouteImport.update({
    id: '/travel-info/luggage',
    path: '/travel-info/luggage',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TravelInfoLostPropertyRoute =
  Char123LocaleChar125TravelInfoLostPropertyRouteImport.update({
    id: '/travel-info/lost-property',
    path: '/travel-info/lost-property',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TimetableLiveRoute =
  Char123LocaleChar125TimetableLiveRouteImport.update({
    id: '/timetable/live',
    path: '/timetable/live',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TimetableAlertsRoute =
  Char123LocaleChar125TimetableAlertsRouteImport.update({
    id: '/timetable/alerts',
    path: '/timetable/alerts',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TicketsPassesRoute =
  Char123LocaleChar125TicketsPassesRouteImport.update({
    id: '/tickets/passes',
    path: '/tickets/passes',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TicketsFaresRoute =
  Char123LocaleChar125TicketsFaresRouteImport.update({
    id: '/tickets/fares',
    path: '/tickets/fares',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TicketsDiscountsRoute =
  Char123LocaleChar125TicketsDiscountsRouteImport.update({
    id: '/tickets/discounts',
    path: '/tickets/discounts',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125StationsIdRoute =
  Char123LocaleChar125StationsIdRouteImport.update({
    id: '/stations/$id',
    path: '/stations/$id',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125NetworkMapRoute =
  Char123LocaleChar125NetworkMapRouteImport.update({
    id: '/network/map',
    path: '/network/map',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125NetworkLinesRoute =
  Char123LocaleChar125NetworkLinesRouteImport.update({
    id: '/network/lines',
    path: '/network/lines',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LegalTermsRoute =
  Char123LocaleChar125LegalTermsRouteImport.update({
    id: '/legal/terms',
    path: '/legal/terms',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LegalRefundsRoute =
  Char123LocaleChar125LegalRefundsRouteImport.update({
    id: '/legal/refunds',
    path: '/legal/refunds',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LegalPrivacyRoute =
  Char123LocaleChar125LegalPrivacyRouteImport.update({
    id: '/legal/privacy',
    path: '/legal/privacy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LegalCookiesRoute =
  Char123LocaleChar125LegalCookiesRouteImport.update({
    id: '/legal/cookies',
    path: '/legal/cookies',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountIndexRoute =
  Char123LocaleChar125AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountTravellersRoute =
  Char123LocaleChar125AuthenticatedAccountTravellersRouteImport.update({
    id: '/account/travellers',
    path: '/account/travellers',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountPaymentRoute =
  Char123LocaleChar125AuthenticatedAccountPaymentRouteImport.update({
    id: '/account/payment',
    path: '/account/payment',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountNotificationsRoute =
  Char123LocaleChar125AuthenticatedAccountNotificationsRouteImport.update({
    id: '/account/notifications',
    path: '/account/notifications',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountJourneysRoute =
  Char123LocaleChar125AuthenticatedAccountJourneysRouteImport.update({
    id: '/account/journeys',
    path: '/account/journeys',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)
const Char123LocaleChar125AuthenticatedAccountBookingsRoute =
  Char123LocaleChar125AuthenticatedAccountBookingsRouteImport.update({
    id: '/account/bookings',
    path: '/account/bookings',
    getParentRoute: () => Char123LocaleChar125AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/accessibility': typeof Char123LocaleChar125AccessibilityRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/class': typeof Char123LocaleChar125ClassRoute
  '/{-$locale}/confirmation': typeof Char123LocaleChar125ConfirmationRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/help': typeof Char123LocaleChar125HelpRoute
  '/{-$locale}/investors': typeof Char123LocaleChar125InvestorsRoute
  '/{-$locale}/news': typeof Char123LocaleChar125NewsRoute
  '/{-$locale}/passenger': typeof Char123LocaleChar125PassengerRoute
  '/{-$locale}/payment': typeof Char123LocaleChar125PaymentRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/legal/cookies': typeof Char123LocaleChar125LegalCookiesRoute
  '/{-$locale}/legal/privacy': typeof Char123LocaleChar125LegalPrivacyRoute
  '/{-$locale}/legal/refunds': typeof Char123LocaleChar125LegalRefundsRoute
  '/{-$locale}/legal/terms': typeof Char123LocaleChar125LegalTermsRoute
  '/{-$locale}/network/lines': typeof Char123LocaleChar125NetworkLinesRoute
  '/{-$locale}/network/map': typeof Char123LocaleChar125NetworkMapRoute
  '/{-$locale}/stations/$id': typeof Char123LocaleChar125StationsIdRoute
  '/{-$locale}/tickets/discounts': typeof Char123LocaleChar125TicketsDiscountsRoute
  '/{-$locale}/tickets/fares': typeof Char123LocaleChar125TicketsFaresRoute
  '/{-$locale}/tickets/passes': typeof Char123LocaleChar125TicketsPassesRoute
  '/{-$locale}/timetable/alerts': typeof Char123LocaleChar125TimetableAlertsRoute
  '/{-$locale}/timetable/live': typeof Char123LocaleChar125TimetableLiveRoute
  '/{-$locale}/travel-info/lost-property': typeof Char123LocaleChar125TravelInfoLostPropertyRoute
  '/{-$locale}/travel-info/luggage': typeof Char123LocaleChar125TravelInfoLuggageRoute
  '/{-$locale}/travel-info/safety': typeof Char123LocaleChar125TravelInfoSafetyRoute
  '/{-$locale}/stations/': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/timetable/': typeof Char123LocaleChar125TimetableIndexRoute
  '/{-$locale}/account/bookings': typeof Char123LocaleChar125AuthenticatedAccountBookingsRoute
  '/{-$locale}/account/journeys': typeof Char123LocaleChar125AuthenticatedAccountJourneysRoute
  '/{-$locale}/account/notifications': typeof Char123LocaleChar125AuthenticatedAccountNotificationsRoute
  '/{-$locale}/account/payment': typeof Char123LocaleChar125AuthenticatedAccountPaymentRoute
  '/{-$locale}/account/travellers': typeof Char123LocaleChar125AuthenticatedAccountTravellersRoute
  '/{-$locale}/account/': typeof Char123LocaleChar125AuthenticatedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/accessibility': typeof Char123LocaleChar125AccessibilityRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/class': typeof Char123LocaleChar125ClassRoute
  '/{-$locale}/confirmation': typeof Char123LocaleChar125ConfirmationRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/help': typeof Char123LocaleChar125HelpRoute
  '/{-$locale}/investors': typeof Char123LocaleChar125InvestorsRoute
  '/{-$locale}/news': typeof Char123LocaleChar125NewsRoute
  '/{-$locale}/passenger': typeof Char123LocaleChar125PassengerRoute
  '/{-$locale}/payment': typeof Char123LocaleChar125PaymentRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/legal/cookies': typeof Char123LocaleChar125LegalCookiesRoute
  '/{-$locale}/legal/privacy': typeof Char123LocaleChar125LegalPrivacyRoute
  '/{-$locale}/legal/refunds': typeof Char123LocaleChar125LegalRefundsRoute
  '/{-$locale}/legal/terms': typeof Char123LocaleChar125LegalTermsRoute
  '/{-$locale}/network/lines': typeof Char123LocaleChar125NetworkLinesRoute
  '/{-$locale}/network/map': typeof Char123LocaleChar125NetworkMapRoute
  '/{-$locale}/stations/$id': typeof Char123LocaleChar125StationsIdRoute
  '/{-$locale}/tickets/discounts': typeof Char123LocaleChar125TicketsDiscountsRoute
  '/{-$locale}/tickets/fares': typeof Char123LocaleChar125TicketsFaresRoute
  '/{-$locale}/tickets/passes': typeof Char123LocaleChar125TicketsPassesRoute
  '/{-$locale}/timetable/alerts': typeof Char123LocaleChar125TimetableAlertsRoute
  '/{-$locale}/timetable/live': typeof Char123LocaleChar125TimetableLiveRoute
  '/{-$locale}/travel-info/lost-property': typeof Char123LocaleChar125TravelInfoLostPropertyRoute
  '/{-$locale}/travel-info/luggage': typeof Char123LocaleChar125TravelInfoLuggageRoute
  '/{-$locale}/travel-info/safety': typeof Char123LocaleChar125TravelInfoSafetyRoute
  '/{-$locale}/stations': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/timetable': typeof Char123LocaleChar125TimetableIndexRoute
  '/{-$locale}/account/bookings': typeof Char123LocaleChar125AuthenticatedAccountBookingsRoute
  '/{-$locale}/account/journeys': typeof Char123LocaleChar125AuthenticatedAccountJourneysRoute
  '/{-$locale}/account/notifications': typeof Char123LocaleChar125AuthenticatedAccountNotificationsRoute
  '/{-$locale}/account/payment': typeof Char123LocaleChar125AuthenticatedAccountPaymentRoute
  '/{-$locale}/account/travellers': typeof Char123LocaleChar125AuthenticatedAccountTravellersRoute
  '/{-$locale}/account': typeof Char123LocaleChar125AuthenticatedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/_authenticated': typeof Char123LocaleChar125AuthenticatedRouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/accessibility': typeof Char123LocaleChar125AccessibilityRoute
  '/{-$locale}/auth': typeof Char123LocaleChar125AuthRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/class': typeof Char123LocaleChar125ClassRoute
  '/{-$locale}/confirmation': typeof Char123LocaleChar125ConfirmationRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/help': typeof Char123LocaleChar125HelpRoute
  '/{-$locale}/investors': typeof Char123LocaleChar125InvestorsRoute
  '/{-$locale}/news': typeof Char123LocaleChar125NewsRoute
  '/{-$locale}/passenger': typeof Char123LocaleChar125PassengerRoute
  '/{-$locale}/payment': typeof Char123LocaleChar125PaymentRoute
  '/{-$locale}/search': typeof Char123LocaleChar125SearchRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/legal/cookies': typeof Char123LocaleChar125LegalCookiesRoute
  '/{-$locale}/legal/privacy': typeof Char123LocaleChar125LegalPrivacyRoute
  '/{-$locale}/legal/refunds': typeof Char123LocaleChar125LegalRefundsRoute
  '/{-$locale}/legal/terms': typeof Char123LocaleChar125LegalTermsRoute
  '/{-$locale}/network/lines': typeof Char123LocaleChar125NetworkLinesRoute
  '/{-$locale}/network/map': typeof Char123LocaleChar125NetworkMapRoute
  '/{-$locale}/stations/$id': typeof Char123LocaleChar125StationsIdRoute
  '/{-$locale}/tickets/discounts': typeof Char123LocaleChar125TicketsDiscountsRoute
  '/{-$locale}/tickets/fares': typeof Char123LocaleChar125TicketsFaresRoute
  '/{-$locale}/tickets/passes': typeof Char123LocaleChar125TicketsPassesRoute
  '/{-$locale}/timetable/alerts': typeof Char123LocaleChar125TimetableAlertsRoute
  '/{-$locale}/timetable/live': typeof Char123LocaleChar125TimetableLiveRoute
  '/{-$locale}/travel-info/lost-property': typeof Char123LocaleChar125TravelInfoLostPropertyRoute
  '/{-$locale}/travel-info/luggage': typeof Char123LocaleChar125TravelInfoLuggageRoute
  '/{-$locale}/travel-info/safety': typeof Char123LocaleChar125TravelInfoSafetyRoute
  '/{-$locale}/stations/': typeof Char123LocaleChar125StationsIndexRoute
  '/{-$locale}/timetable/': typeof Char123LocaleChar125TimetableIndexRoute
  '/{-$locale}/_authenticated/account/bookings': typeof Char123LocaleChar125AuthenticatedAccountBookingsRoute
  '/{-$locale}/_authenticated/account/journeys': typeof Char123LocaleChar125AuthenticatedAccountJourneysRoute
  '/{-$locale}/_authenticated/account/notifications': typeof Char123LocaleChar125AuthenticatedAccountNotificationsRoute
  '/{-$locale}/_authenticated/account/payment': typeof Char123LocaleChar125AuthenticatedAccountPaymentRoute
  '/{-$locale}/_authenticated/account/travellers': typeof Char123LocaleChar125AuthenticatedAccountTravellersRoute
  '/{-$locale}/_authenticated/account/': typeof Char123LocaleChar125AuthenticatedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/accessibility'
    | '/{-$locale}/auth'
    | '/{-$locale}/careers'
    | '/{-$locale}/class'
    | '/{-$locale}/confirmation'
    | '/{-$locale}/contact'
    | '/{-$locale}/help'
    | '/{-$locale}/investors'
    | '/{-$locale}/news'
    | '/{-$locale}/passenger'
    | '/{-$locale}/payment'
    | '/{-$locale}/search'
    | '/{-$locale}/'
    | '/{-$locale}/legal/cookies'
    | '/{-$locale}/legal/privacy'
    | '/{-$locale}/legal/refunds'
    | '/{-$locale}/legal/terms'
    | '/{-$locale}/network/lines'
    | '/{-$locale}/network/map'
    | '/{-$locale}/stations/$id'
    | '/{-$locale}/tickets/discounts'
    | '/{-$locale}/tickets/fares'
    | '/{-$locale}/tickets/passes'
    | '/{-$locale}/timetable/alerts'
    | '/{-$locale}/timetable/live'
    | '/{-$locale}/travel-info/lost-property'
    | '/{-$locale}/travel-info/luggage'
    | '/{-$locale}/travel-info/safety'
    | '/{-$locale}/stations/'
    | '/{-$locale}/timetable/'
    | '/{-$locale}/account/bookings'
    | '/{-$locale}/account/journeys'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/payment'
    | '/{-$locale}/account/travellers'
    | '/{-$locale}/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/{-$locale}'
    | '/{-$locale}/about'
    | '/{-$locale}/accessibility'
    | '/{-$locale}/auth'
    | '/{-$locale}/careers'
    | '/{-$locale}/class'
    | '/{-$locale}/confirmation'
    | '/{-$locale}/contact'
    | '/{-$locale}/help'
    | '/{-$locale}/investors'
    | '/{-$locale}/news'
    | '/{-$locale}/passenger'
    | '/{-$locale}/payment'
    | '/{-$locale}/search'
    | '/{-$locale}/legal/cookies'
    | '/{-$locale}/legal/privacy'
    | '/{-$locale}/legal/refunds'
    | '/{-$locale}/legal/terms'
    | '/{-$locale}/network/lines'
    | '/{-$locale}/network/map'
    | '/{-$locale}/stations/$id'
    | '/{-$locale}/tickets/discounts'
    | '/{-$locale}/tickets/fares'
    | '/{-$locale}/tickets/passes'
    | '/{-$locale}/timetable/alerts'
    | '/{-$locale}/timetable/live'
    | '/{-$locale}/travel-info/lost-property'
    | '/{-$locale}/travel-info/luggage'
    | '/{-$locale}/travel-info/safety'
    | '/{-$locale}/stations'
    | '/{-$locale}/timetable'
    | '/{-$locale}/account/bookings'
    | '/{-$locale}/account/journeys'
    | '/{-$locale}/account/notifications'
    | '/{-$locale}/account/payment'
    | '/{-$locale}/account/travellers'
    | '/{-$locale}/account'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/sitemap.xml'
    | '/{-$locale}/_authenticated'
    | '/{-$locale}/about'
    | '/{-$locale}/accessibility'
    | '/{-$locale}/auth'
    | '/{-$locale}/careers'
    | '/{-$locale}/class'
    | '/{-$locale}/confirmation'
    | '/{-$locale}/contact'
    | '/{-$locale}/help'
    | '/{-$locale}/investors'
    | '/{-$locale}/news'
    | '/{-$locale}/passenger'
    | '/{-$locale}/payment'
    | '/{-$locale}/search'
    | '/{-$locale}/'
    | '/{-$locale}/legal/cookies'
    | '/{-$locale}/legal/privacy'
    | '/{-$locale}/legal/refunds'
    | '/{-$locale}/legal/terms'
    | '/{-$locale}/network/lines'
    | '/{-$locale}/network/map'
    | '/{-$locale}/stations/$id'
    | '/{-$locale}/tickets/discounts'
    | '/{-$locale}/tickets/fares'
    | '/{-$locale}/tickets/passes'
    | '/{-$locale}/timetable/alerts'
    | '/{-$locale}/timetable/live'
    | '/{-$locale}/travel-info/lost-property'
    | '/{-$locale}/travel-info/luggage'
    | '/{-$locale}/travel-info/safety'
    | '/{-$locale}/stations/'
    | '/{-$locale}/timetable/'
    | '/{-$locale}/_authenticated/account/bookings'
    | '/{-$locale}/_authenticated/account/journeys'
    | '/{-$locale}/_authenticated/account/notifications'
    | '/{-$locale}/_authenticated/account/payment'
    | '/{-$locale}/_authenticated/account/travellers'
    | '/{-$locale}/_authenticated/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/search': {
      id: '/{-$locale}/search'
      path: '/search'
      fullPath: '/{-$locale}/search'
      preLoaderRoute: typeof Char123LocaleChar125SearchRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/payment': {
      id: '/{-$locale}/payment'
      path: '/payment'
      fullPath: '/{-$locale}/payment'
      preLoaderRoute: typeof Char123LocaleChar125PaymentRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/passenger': {
      id: '/{-$locale}/passenger'
      path: '/passenger'
      fullPath: '/{-$locale}/passenger'
      preLoaderRoute: typeof Char123LocaleChar125PassengerRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/news': {
      id: '/{-$locale}/news'
      path: '/news'
      fullPath: '/{-$locale}/news'
      preLoaderRoute: typeof Char123LocaleChar125NewsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/investors': {
      id: '/{-$locale}/investors'
      path: '/investors'
      fullPath: '/{-$locale}/investors'
      preLoaderRoute: typeof Char123LocaleChar125InvestorsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/help': {
      id: '/{-$locale}/help'
      path: '/help'
      fullPath: '/{-$locale}/help'
      preLoaderRoute: typeof Char123LocaleChar125HelpRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/confirmation': {
      id: '/{-$locale}/confirmation'
      path: '/confirmation'
      fullPath: '/{-$locale}/confirmation'
      preLoaderRoute: typeof Char123LocaleChar125ConfirmationRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/class': {
      id: '/{-$locale}/class'
      path: '/class'
      fullPath: '/{-$locale}/class'
      preLoaderRoute: typeof Char123LocaleChar125ClassRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/careers': {
      id: '/{-$locale}/careers'
      path: '/careers'
      fullPath: '/{-$locale}/careers'
      preLoaderRoute: typeof Char123LocaleChar125CareersRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/auth': {
      id: '/{-$locale}/auth'
      path: '/auth'
      fullPath: '/{-$locale}/auth'
      preLoaderRoute: typeof Char123LocaleChar125AuthRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/accessibility': {
      id: '/{-$locale}/accessibility'
      path: '/accessibility'
      fullPath: '/{-$locale}/accessibility'
      preLoaderRoute: typeof Char123LocaleChar125AccessibilityRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_authenticated': {
      id: '/{-$locale}/_authenticated'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/timetable/': {
      id: '/{-$locale}/timetable/'
      path: '/timetable'
      fullPath: '/{-$locale}/timetable/'
      preLoaderRoute: typeof Char123LocaleChar125TimetableIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/stations/': {
      id: '/{-$locale}/stations/'
      path: '/stations'
      fullPath: '/{-$locale}/stations/'
      preLoaderRoute: typeof Char123LocaleChar125StationsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/travel-info/safety': {
      id: '/{-$locale}/travel-info/safety'
      path: '/travel-info/safety'
      fullPath: '/{-$locale}/travel-info/safety'
      preLoaderRoute: typeof Char123LocaleChar125TravelInfoSafetyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/travel-info/luggage': {
      id: '/{-$locale}/travel-info/luggage'
      path: '/travel-info/luggage'
      fullPath: '/{-$locale}/travel-info/luggage'
      preLoaderRoute: typeof Char123LocaleChar125TravelInfoLuggageRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/travel-info/lost-property': {
      id: '/{-$locale}/travel-info/lost-property'
      path: '/travel-info/lost-property'
      fullPath: '/{-$locale}/travel-info/lost-property'
      preLoaderRoute: typeof Char123LocaleChar125TravelInfoLostPropertyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/timetable/live': {
      id: '/{-$locale}/timetable/live'
      path: '/timetable/live'
      fullPath: '/{-$locale}/timetable/live'
      preLoaderRoute: typeof Char123LocaleChar125TimetableLiveRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/timetable/alerts': {
      id: '/{-$locale}/timetable/alerts'
      path: '/timetable/alerts'
      fullPath: '/{-$locale}/timetable/alerts'
      preLoaderRoute: typeof Char123LocaleChar125TimetableAlertsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/tickets/passes': {
      id: '/{-$locale}/tickets/passes'
      path: '/tickets/passes'
      fullPath: '/{-$locale}/tickets/passes'
      preLoaderRoute: typeof Char123LocaleChar125TicketsPassesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/tickets/fares': {
      id: '/{-$locale}/tickets/fares'
      path: '/tickets/fares'
      fullPath: '/{-$locale}/tickets/fares'
      preLoaderRoute: typeof Char123LocaleChar125TicketsFaresRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/tickets/discounts': {
      id: '/{-$locale}/tickets/discounts'
      path: '/tickets/discounts'
      fullPath: '/{-$locale}/tickets/discounts'
      preLoaderRoute: typeof Char123LocaleChar125TicketsDiscountsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/stations/$id': {
      id: '/{-$locale}/stations/$id'
      path: '/stations/$id'
      fullPath: '/{-$locale}/stations/$id'
      preLoaderRoute: typeof Char123LocaleChar125StationsIdRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/network/map': {
      id: '/{-$locale}/network/map'
      path: '/network/map'
      fullPath: '/{-$locale}/network/map'
      preLoaderRoute: typeof Char123LocaleChar125NetworkMapRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/network/lines': {
      id: '/{-$locale}/network/lines'
      path: '/network/lines'
      fullPath: '/{-$locale}/network/lines'
      preLoaderRoute: typeof Char123LocaleChar125NetworkLinesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/legal/terms': {
      id: '/{-$locale}/legal/terms'
      path: '/legal/terms'
      fullPath: '/{-$locale}/legal/terms'
      preLoaderRoute: typeof Char123LocaleChar125LegalTermsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/legal/refunds': {
      id: '/{-$locale}/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/{-$locale}/legal/refunds'
      preLoaderRoute: typeof Char123LocaleChar125LegalRefundsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/legal/privacy': {
      id: '/{-$locale}/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/{-$locale}/legal/privacy'
      preLoaderRoute: typeof Char123LocaleChar125LegalPrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/legal/cookies': {
      id: '/{-$locale}/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/{-$locale}/legal/cookies'
      preLoaderRoute: typeof Char123LocaleChar125LegalCookiesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/_authenticated/account/': {
      id: '/{-$locale}/_authenticated/account/'
      path: '/account'
      fullPath: '/{-$locale}/account/'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
    '/{-$locale}/_authenticated/account/travellers': {
      id: '/{-$locale}/_authenticated/account/travellers'
      path: '/account/travellers'
      fullPath: '/{-$locale}/account/travellers'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountTravellersRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
    '/{-$locale}/_authenticated/account/payment': {
      id: '/{-$locale}/_authenticated/account/payment'
      path: '/account/payment'
      fullPath: '/{-$locale}/account/payment'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountPaymentRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
    '/{-$locale}/_authenticated/account/notifications': {
      id: '/{-$locale}/_authenticated/account/notifications'
      path: '/account/notifications'
      fullPath: '/{-$locale}/account/notifications'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
    '/{-$locale}/_authenticated/account/journeys': {
      id: '/{-$locale}/_authenticated/account/journeys'
      path: '/account/journeys'
      fullPath: '/{-$locale}/account/journeys'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountJourneysRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
    '/{-$locale}/_authenticated/account/bookings': {
      id: '/{-$locale}/_authenticated/account/bookings'
      path: '/account/bookings'
      fullPath: '/{-$locale}/account/bookings'
      preLoaderRoute: typeof Char123LocaleChar125AuthenticatedAccountBookingsRouteImport
      parentRoute: typeof Char123LocaleChar125AuthenticatedRouteRoute
    }
  }
}

interface Char123LocaleChar125AuthenticatedRouteRouteChildren {
  Char123LocaleChar125AuthenticatedAccountBookingsRoute: typeof Char123LocaleChar125AuthenticatedAccountBookingsRoute
  Char123LocaleChar125AuthenticatedAccountJourneysRoute: typeof Char123LocaleChar125AuthenticatedAccountJourneysRoute
  Char123LocaleChar125AuthenticatedAccountNotificationsRoute: typeof Char123LocaleChar125AuthenticatedAccountNotificationsRoute
  Char123LocaleChar125AuthenticatedAccountPaymentRoute: typeof Char123LocaleChar125AuthenticatedAccountPaymentRoute
  Char123LocaleChar125AuthenticatedAccountTravellersRoute: typeof Char123LocaleChar125AuthenticatedAccountTravellersRoute
  Char123LocaleChar125AuthenticatedAccountIndexRoute: typeof Char123LocaleChar125AuthenticatedAccountIndexRoute
}

const Char123LocaleChar125AuthenticatedRouteRouteChildren: Char123LocaleChar125AuthenticatedRouteRouteChildren =
  {
    Char123LocaleChar125AuthenticatedAccountBookingsRoute:
      Char123LocaleChar125AuthenticatedAccountBookingsRoute,
    Char123LocaleChar125AuthenticatedAccountJourneysRoute:
      Char123LocaleChar125AuthenticatedAccountJourneysRoute,
    Char123LocaleChar125AuthenticatedAccountNotificationsRoute:
      Char123LocaleChar125AuthenticatedAccountNotificationsRoute,
    Char123LocaleChar125AuthenticatedAccountPaymentRoute:
      Char123LocaleChar125AuthenticatedAccountPaymentRoute,
    Char123LocaleChar125AuthenticatedAccountTravellersRoute:
      Char123LocaleChar125AuthenticatedAccountTravellersRoute,
    Char123LocaleChar125AuthenticatedAccountIndexRoute:
      Char123LocaleChar125AuthenticatedAccountIndexRoute,
  }

const Char123LocaleChar125AuthenticatedRouteRouteWithChildren =
  Char123LocaleChar125AuthenticatedRouteRoute._addFileChildren(
    Char123LocaleChar125AuthenticatedRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AuthenticatedRouteRoute: typeof Char123LocaleChar125AuthenticatedRouteRouteWithChildren
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AccessibilityRoute: typeof Char123LocaleChar125AccessibilityRoute
  Char123LocaleChar125AuthRoute: typeof Char123LocaleChar125AuthRoute
  Char123LocaleChar125CareersRoute: typeof Char123LocaleChar125CareersRoute
  Char123LocaleChar125ClassRoute: typeof Char123LocaleChar125ClassRoute
  Char123LocaleChar125ConfirmationRoute: typeof Char123LocaleChar125ConfirmationRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125HelpRoute: typeof Char123LocaleChar125HelpRoute
  Char123LocaleChar125InvestorsRoute: typeof Char123LocaleChar125InvestorsRoute
  Char123LocaleChar125NewsRoute: typeof Char123LocaleChar125NewsRoute
  Char123LocaleChar125PassengerRoute: typeof Char123LocaleChar125PassengerRoute
  Char123LocaleChar125PaymentRoute: typeof Char123LocaleChar125PaymentRoute
  Char123LocaleChar125SearchRoute: typeof Char123LocaleChar125SearchRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125LegalCookiesRoute: typeof Char123LocaleChar125LegalCookiesRoute
  Char123LocaleChar125LegalPrivacyRoute: typeof Char123LocaleChar125LegalPrivacyRoute
  Char123LocaleChar125LegalRefundsRoute: typeof Char123LocaleChar125LegalRefundsRoute
  Char123LocaleChar125LegalTermsRoute: typeof Char123LocaleChar125LegalTermsRoute
  Char123LocaleChar125NetworkLinesRoute: typeof Char123LocaleChar125NetworkLinesRoute
  Char123LocaleChar125NetworkMapRoute: typeof Char123LocaleChar125NetworkMapRoute
  Char123LocaleChar125StationsIdRoute: typeof Char123LocaleChar125StationsIdRoute
  Char123LocaleChar125TicketsDiscountsRoute: typeof Char123LocaleChar125TicketsDiscountsRoute
  Char123LocaleChar125TicketsFaresRoute: typeof Char123LocaleChar125TicketsFaresRoute
  Char123LocaleChar125TicketsPassesRoute: typeof Char123LocaleChar125TicketsPassesRoute
  Char123LocaleChar125TimetableAlertsRoute: typeof Char123LocaleChar125TimetableAlertsRoute
  Char123LocaleChar125TimetableLiveRoute: typeof Char123LocaleChar125TimetableLiveRoute
  Char123LocaleChar125TravelInfoLostPropertyRoute: typeof Char123LocaleChar125TravelInfoLostPropertyRoute
  Char123LocaleChar125TravelInfoLuggageRoute: typeof Char123LocaleChar125TravelInfoLuggageRoute
  Char123LocaleChar125TravelInfoSafetyRoute: typeof Char123LocaleChar125TravelInfoSafetyRoute
  Char123LocaleChar125StationsIndexRoute: typeof Char123LocaleChar125StationsIndexRoute
  Char123LocaleChar125TimetableIndexRoute: typeof Char123LocaleChar125TimetableIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AuthenticatedRouteRoute:
      Char123LocaleChar125AuthenticatedRouteRouteWithChildren,
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125AccessibilityRoute:
      Char123LocaleChar125AccessibilityRoute,
    Char123LocaleChar125AuthRoute: Char123LocaleChar125AuthRoute,
    Char123LocaleChar125CareersRoute: Char123LocaleChar125CareersRoute,
    Char123LocaleChar125ClassRoute: Char123LocaleChar125ClassRoute,
    Char123LocaleChar125ConfirmationRoute:
      Char123LocaleChar125ConfirmationRoute,
    Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
    Char123LocaleChar125HelpRoute: Char123LocaleChar125HelpRoute,
    Char123LocaleChar125InvestorsRoute: Char123LocaleChar125InvestorsRoute,
    Char123LocaleChar125NewsRoute: Char123LocaleChar125NewsRoute,
    Char123LocaleChar125PassengerRoute: Char123LocaleChar125PassengerRoute,
    Char123LocaleChar125PaymentRoute: Char123LocaleChar125PaymentRoute,
    Char123LocaleChar125SearchRoute: Char123LocaleChar125SearchRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125LegalCookiesRoute:
      Char123LocaleChar125LegalCookiesRoute,
    Char123LocaleChar125LegalPrivacyRoute:
      Char123LocaleChar125LegalPrivacyRoute,
    Char123LocaleChar125LegalRefundsRoute:
      Char123LocaleChar125LegalRefundsRoute,
    Char123LocaleChar125LegalTermsRoute: Char123LocaleChar125LegalTermsRoute,
    Char123LocaleChar125NetworkLinesRoute:
      Char123LocaleChar125NetworkLinesRoute,
    Char123LocaleChar125NetworkMapRoute: Char123LocaleChar125NetworkMapRoute,
    Char123LocaleChar125StationsIdRoute: Char123LocaleChar125StationsIdRoute,
    Char123LocaleChar125TicketsDiscountsRoute:
      Char123LocaleChar125TicketsDiscountsRoute,
    Char123LocaleChar125TicketsFaresRoute:
      Char123LocaleChar125TicketsFaresRoute,
    Char123LocaleChar125TicketsPassesRoute:
      Char123LocaleChar125TicketsPassesRoute,
    Char123LocaleChar125TimetableAlertsRoute:
      Char123LocaleChar125TimetableAlertsRoute,
    Char123LocaleChar125TimetableLiveRoute:
      Char123LocaleChar125TimetableLiveRoute,
    Char123LocaleChar125TravelInfoLostPropertyRoute:
      Char123LocaleChar125TravelInfoLostPropertyRoute,
    Char123LocaleChar125TravelInfoLuggageRoute:
      Char123LocaleChar125TravelInfoLuggageRoute,
    Char123LocaleChar125TravelInfoSafetyRoute:
      Char123LocaleChar125TravelInfoSafetyRoute,
    Char123LocaleChar125StationsIndexRoute:
      Char123LocaleChar125StationsIndexRoute,
    Char123LocaleChar125TimetableIndexRoute:
      Char123LocaleChar125TimetableIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
